### ISSUE TITLE
Shulker boxes

### ISSUE THREAD

**Issue by Tigergiri** [Lord-of-the-Craft/tracker#1]
Ok shulker boxes have been having some troubles with players when it comes to stacked items that arent naturally stacked. It completely either one) erases all the items in the shulker or two) unstacks to fill the space, overtaking other items if the shulker is full. Leaving to find the items or refunding it. **Most common items that cause this** Drinks, Iron sets (boots, swords.. ets), bows, crossbows, Named items.

**Comment by Nickrocky** [comment]
When you override the stack limit for the itemstack this error occurs, we ran into it when testing on swords, and even enderpearls as they only stack to 16
