### ISSUE TITLE
Full lobby glitch

### ISSUE THREAD

**Issue by StrongBear007** [Lord-of-the-Craft/tracker#10]
Having an issue with the full lobby glitch. When I try to login it, it will tell me that the lobby is full. I will try to get in a few times and I still cant get in. I will even restart my computer and still nothing

**Comment by CommissarVoop** [comment]
Hello there StrongBear007, sorry the hear about the issue you are facing, but we need some more details of the issue, if you have client sided logs or screenshots it could be useful for us. For the next time reports feel free to use this report format ([Click Here](https://github.com/Lord-of-the-Craft/tracker))  this will make a our issue tracking a easier job. But however regarding to server full issue on the main server itself we are aware of the issue some fixes are being made. If you have keep getting this issue feel free to comment here or contact me on discord (Voop#2394).

~Voop

**Comment by Kowaman** [comment]
What domain address are you using to connect to the server, or is this in-game through /lobby ?

**Comment by Kowaman** [comment]
Documented at [MC-16742](https://bugs.mojang.com/browse/MC-162742)
