### ISSUE TITLE
Fractional minas causing wallet limit to be reached at 499/500

### ISSUE THREAD

**Issue by Deer2underscores** [Lord-of-the-Craft/tracker#100]
**Issue**
Can hold 499 but not 500 mina. I think it's due to them having an unseen fractional amount of mina
IGN: _PR0FIT 

**Ticket refence number:**
RTS-56125

**Comment by Kowaman** [comment]
Player had 0.05 mina in account, likely due to mina splitting on death. Will look into assuring this value is sanitized. Balance was corrected for player in question.

**Comment by Deer2underscores** [comment]
Even with the .05 mina being corrected, player cannot reach 500 mina one persona @1
