### ISSUE TITLE
Buttons opening locked doors

### ISSUE THREAD

**Issue by MayRndzz** [Lord-of-the-Craft/tracker#101]
**Minecraft Username**  MayRndz

**Describe the bug**  Placing a button near locked trapdoors and doors bypasses the lock allowing you to break in.

**How did this occur** A player made a modreq reporting the issue after finding it by accident with one of their trapdoors in their shop.

**Expected behavior*** When the button is clicked it should have no effect on locked doors and trapdoors and show the same "This Trapdoor is Locked" message that people get upon regularly. 

**Screenshots If applicable** Being on moderation means I can bypass all locks regardless, so you yourself will need to test it out if you'd like to see.

**Minecraft version:** 1.15.2

**Additional context** N/A

**Comment by Kowaman** [comment]
Couldn't the same abuse be done by just digging through their wall 2 blocks from the door? Not sure if much is gained by patching this, it's against the rules anyways

**Comment by The60th** [comment]
This can be prevent with an LWC flag
