### ISSUE TITLE
Visual duplication of herbs

### ISSUE THREAD

**Issue by Kowaman** [Lord-of-the-Craft/tracker#102]
**Issue**
Occurred with bat's eye, tested on multiple nodes. A number of copies disappeared when harvesting.

**Ticket refence number:**
RTS-55989

**Comment by Kowaman** [comment]
![image](https://user-images.githubusercontent.com/1783849/106676339-b44d8600-6584-11eb-9adc-cf47d3674bcd.png)

**Comment by Nickrocky** [comment]
Fixed in the 1.0.0 update of Vortex
