### ISSUE TITLE
Bug despawning

### ISSUE THREAD

**Issue by Deer2underscores** [Lord-of-the-Craft/tracker#110]
**Issue**
Many tickets recently about horses despawning when logging or disconnecting while riding them, saddle and all.

**Ticket refence number:**
RTS-56499 (Only ticket from recent memory)

**Comment by Deer2underscores** [comment]
Kowa, I assigned it to you mostly just so you can organize it somewhere, or maybe you know the issue. I'm not sure what project to place this under.

**Comment by Kowaman** [comment]
Related to #106
