### ISSUE TITLE
Sit plugin tping players back to previous chairs

### ISSUE THREAD

**Issue by MCVDK** [Lord-of-the-Craft/tracker#114]
**Issue**
Sometimes when sitting and standing (sometimes after repeating such a couple of times) the sit plugin TPs the person back to the chair which the person was attempting to sit on previously. 

(from OrenIsBad)

**Ticket refence number:**
RTS-57212

**Comment by FallenVibe** [comment]
Can confirm that this appears to happen during lag spikes. It also seems to occasionally occur in the minutes before restarts. Not sure how "fixable" this really is.

**Comment by The60th** [comment]
I think this was an issue with 1.16.5 + other client version
Can you confirm this still happens? 
@FallenVibe 
The issue was something with the demount events to getting handled properly and demounting being fully client side

**Comment by FallenVibe** [comment]
Still confirmed, though it's been shown to me that it doesn't need to happen during lag spikes/restarts.

There are a couple of players that have shown me the ability to sit down onto a slab and then teleport off, but they weren't willing to share HOW it's done.

@The60th

**Comment by The60th** [comment]
@FallenVibe  
Yeah I remember finding this way back in the summer.
Basically you just spam click and shift on a slab and at some point you will get desync'd where your off the slab on your screen but on the slab for everyone else. 

I thought it was an issue with versions so a good question could be which versions are they on when it happens?
