### ISSUE TITLE
Herb harvesting bug

### ISSUE THREAD

**Issue by Chorale18** [Lord-of-the-Craft/tracker#115]
**Issue**
The player has stated that oftentimes, herbs can be seen floating and it will look like it has been harvested even though it hasn't. It's just invisible. In turn, the herbs stay visible even though they have been harvested. There also appears to be an issue with harvesting messages. Sometimes there will be one, and sometimes there will not. The player has sent screenshots which can be provided to the technician upon request. 

**Ticket refence number:**
RTS- #57296

**Comment by Nickrocky** [comment]
Provide the screenshots if possible that would be extremely helpful

**Comment by Nickrocky** [comment]
I'm pretty sure I was able to fix this in the Node Refactor, the issue has been resolved as of Vortex 1.0.0
