### ISSUE TITLE
Crawling spawning barriers

### ISSUE THREAD

**Issue by Deer2underscores** [Lord-of-the-Craft/tracker#118]
**Issue**
Crawling spawns infinite barrier blocks, thanks fucking sutica. -The homie, nickrocky

**Ticket refence number:**
RTS-57528

**Comment by MCVDK** [comment]
Similar thing occurs with sitting now.

**Comment by Kowaman** [comment]
@MCVDK What do you mean? I've seen no issues with Chairs, the code is unrelated to the crawling mechanic.

**Comment by MCVDK** [comment]
@Kowaman Further investigation can happen but upon rising from a chair there seemed to be spawned a barrier block above the location of the individual (happened to myself once too) which had to be removed with LC. I'll attempt to recreate though it might've been an accidental entry into (brief) crawl once rising from the chair which could've caused such issue.

**Comment by Kowaman** [comment]
@MCVDK The barrier blocks spawned with crawling are fake, perhaps the crawling detection is picking up the shift click to exit the chair, however.

@CommissarVoop Have the block update be sent to set the barrier block back to air if they exit crawling.

**Comment by CommissarVoop** [comment]
An Update has been pushed that should resolve the issue with the barrier blocks!
