### ISSUE TITLE
[tgrt] Consistent Connection Issue

### ISSUE THREAD

**Issue by MCVDK** [Lord-of-the-Craft/tracker#120]
**Issue**
" I can log on but after about 5 seconds chunks stop loading and I get booted off shortly after. Every single log. I've even been pm'd on discord by people noticing the tgrt online-offline spam. I can interact with the server for about 5 seconds. Even managed to ss to cloud temple just incase it was the location but nope. Dc'd every time" - TGRT

It seems there an issue greater than the issue present with the typical disconnection issue that we have experienced. 

Inquire with tgrt#5309

**Ticket refence number:**
No RTS -- mentioned through discord.

**Comment by Kowaman** [comment]
Reported for Ryxark as well, ticket 57211
