### ISSUE TITLE
Horse egg double-spawn

### ISSUE THREAD

**Issue by Deer2underscores** [Lord-of-the-Craft/tracker#123]
**Issue**
Player claimed /edit name on a horse spawn egg made it infinitely useable. I tried it on dev, didn't work. I had a mod help me try it on main and it somewhat worked. It spawned 2 horse instead of one. Only works in ranching tile

**Ticket refence number:**
RTS-57977

**Comment by FallenVibe** [comment]
Tested with mod on ranching and non-ranching tiles. Seemed to be fixed with vortex removal.
