### ISSUE TITLE
Infinite jumpboost caused by disconnecting while crawling 

### ISSUE THREAD

**Issue by MCVDK** [Lord-of-the-Craft/tracker#124]
**Issue**
Crawling beneath an otherwise uncrawlable block (meaning the barrier block is above you) and then being disconnected from the server causes the player to have infinite jump boost (255) -- which means the player cannot jump.

[Screenshot of Effect](https://cdn.discordapp.com/attachments/813923568458530827/813923578126401543/unknown.png)
[Video of Bug (Occurs at 3:10)](https://youtu.be/3D8n6XTfTws?t=190)

**Ticket refence number:**
RTS-58037

**Comment by CommissarVoop** [comment]
Issue would be resolved now! Thank you.
