### ISSUE TITLE
Soulbind durability

### ISSUE THREAD

**Issue by Deer2underscores** [Lord-of-the-Craft/tracker#126]
**Issue**
Damage to item durability on items that are soulbound.

Soulbind item
Hit person with item if it's a tool
Durability ticks down when it shouldn't

**Ticket refence number:**
RTS- 58154 | 58339

**Comment by Kowaman** [comment]
@Nickrocky Do you think this is Vortex? I don't think this should be happening in Bound, I'm certain I cancel the event.

**Comment by FallenVibe** [comment]
After testing, seems to be fixed with vortex removal.
