### ISSUE TITLE
Horses not porting with ferries

### ISSUE THREAD

**Issue by grandpablue** [Lord-of-the-Craft/tracker#128]
**Issue**
Horsey didn't port over when using a ferry warp. The horse didn't die, I tossed in my conversation with Remeron.

**Ticket refence number:**
RTS-#58490

![image](https://user-images.githubusercontent.com/79768296/109433354-861d6380-79d5-11eb-91ea-2aec2a4cfe18.png)

**Comment by Nickrocky** [comment]
This is due to serverload, the horse is actually there if they relog. Its super annoying but its technically a non-issue.

**Comment by Nickrocky** [comment]
After a patch today around 1:10pm est this bug was fixed.
