### ISSUE TITLE
SS Pillar binding bug - can't bind because wants me to hold SS when I hold tome.

### ISSUE THREAD

**Issue by Mordhaund** [Lord-of-the-Craft/tracker#135]
**Minecraft Username**
Mordhaund

**Describe the bug**
Trying to use the new SS pillar, tried to imbue my pillar after placing down the 3 blocks of redstone. Bought an Uncommon Soulbinding Tome. Held it in my hand, and it asked for me to hold a soulstone. Then held my soulstone in my hand, and it's asking me to hold the tome. I then held my SS in my main hand and tome in my offhand, asks for the tome. I then held tome in main hand and SS in offhand, and asks for the SS.

**How did this occur**
Coordinates 1107 -3179 is where my lair is where I placed the pillar. I got Commissar_Voop involved and told him about the bug, and we tried some experimentation to get it to work. He was able to imbue the pillar, but I wasn't. I'd bought an uncommon ss tome from spawn and had  tried to use it, only to find out that this was a bug.

**Expected behavior**
I'd expect, when holding the tome, for it to imbue the Pillar and a green potion effect happens, which is what happened when Voop tried it.

**Screenshots**
https://gyazo.com/d20d5f9f1c1e13f595064010f2e35462

**Minecraft version:**
1.15.2

**Additional context**
N/A

**Comment by CommissarVoop** [comment]
A Patch has been applied to resolve this issue.
