### ISSUE TITLE
GMBANK

### ISSUE THREAD

**Issue by Crevel1** [Lord-of-the-Craft/tracker#14]
Essentially, I made a deposit into the gmbank using /gmbank and the deposit worked. However, the problem is with showing the history of gmbank deposits/withdrawals. Despite "GM Bank History" claiming that it will review the last ten bank deposits, it only shows deposits from February or March. Clicking "Shop Receipts" sends back an "Invalid syntax. Use /gmbank." error. I don't know about you guys but I wouldn't want to risk the chance of corrupt uber hax0r moderators keeping the money and they would get away with it because our ability to see recent deposits is buggered. Furthermore, it also provides evidence of payment if the payer is asked about it so they can contact the moderator who handled the payment for a screenshot.

**Comment by Kowaman** [comment]
https://github.com/Lord-of-the-Craft/lotc-master-showandsell

**Comment by Crevel1** [comment]
Thank you. I can always trust the Lord of the Craft's Technical Team when I am in need of technical support.
