### ISSUE TITLE
/edit rp bugs out the soulbind tag

### ISSUE THREAD

**Issue by Deer2underscores** [Lord-of-the-Craft/tracker#140]
**Issue**
If you have a soulbound item and you do /edit rp it will keep it's soulbind I/II tag but it won't actually be soulbound.

Me and the player were able to fix it by applying a new /soulbind to the items then removing the new soulbind with /soulbind unbind. This got rid of the Soulbound I tag. After this I had a mod grant the player enough tokens to replace the lost ones.

Workaround: /soulbind unbind your items before you do /edit rp, then rebind them after.

**Ticket refence number:**
RTS-60494

**Comment by The60th** [comment]
Will be fixed with itemedit patch
/edit roleplay currently broken

**Comment by The60th** [comment]
Fix work in progress by myself
