### ISSUE TITLE
The Eternal Hoe

### ISSUE THREAD

**Issue by KingKunuk** [Lord-of-the-Craft/tracker#141]
**Minecraft Username**
King_Kunuk

**Describe the bug**
The bug is quite simple. Whenever a hoe gets to low durability, if you left click break a crop block, the hoe will gain most of it's durability back. 

**How did this occur**
IT happened by complete accident. It is really easy to repdouce. Simply get a hoe (I was using stone) to half way/low durability, then left click a crop block. The bug will then occur 

**Expected behavior**
The bug essentially recharges a hoe to full durability, allowing it to be used without end

**Screenshots**
N/A

**Minecraft version:**
I am playing on 1.6

**Additional context**
N/A

**Comment by FallenVibe** [comment]
After testing with vanilla hoes, seems to no longer be an issue.
