### ISSUE TITLE
Signed books not stacking + unclear issues with showandsell

### ISSUE THREAD

**Issue by Chorale18** [Lord-of-the-Craft/tracker#142]
**Issue**
Signed books are not stacking, and the player also says that there are issues with books and shops. I went onto the dev server and confirmed that signed books do not stack, but I believe this behavior to be intentional. As far as the shops issue, I have requested more information from the player and will edit the issue once further contact is made.

**Ticket refence number:**
RTS- #60459

**Comment by Kowaman** [comment]
Related to #30
