### ISSUE TITLE
/edit roleplay clears the first sentence of an item description if it's long

### ISSUE THREAD

**Issue by grandpablue** [Lord-of-the-Craft/tracker#147]
**Issue**
if you /edit roleplay an item with a decently long description it will wipe out the first sentence or so of the description. This doesn't seem to be an issue if the description is short. Additionally, if you clear a description then go to set the item to a roleplay item again, you're given an error warning and told to contact a dev.
![image](https://user-images.githubusercontent.com/79768296/117608265-59976d80-b123-11eb-8ffc-c26c4157c2b5.png)

**Ticket refence number:**
RTS- 64400

**Comment by The60th** [comment]
Will be fixed with itemedit patch
/edit roleplay currently broken

**Comment by The60th** [comment]
Fix work in progress by myself
