### ISSUE TITLE
/edit roleplay unstacks ferum, aurum

### ISSUE THREAD

**Issue by grandpablue** [Lord-of-the-Craft/tracker#148]
**Issue**
Had a player /edit roleplay stack of ferum and aurum with glow effect on them, after editing the stack the glow effect was lost and the stack was reduced from 8  ingots to 1

**Ticket refence number:**
RTS-64497, 66596

**Comment by grandpablue** [comment]
Seems to be an ongoing issue with most vortex items - editing them after they're stacked will reduce the stack to one

**Comment by FallenVibe** [comment]
After testing, seems to no longer occur with Vortex Removal.
