### ISSUE TITLE
Shifting on slabs while in 1.16 visually glitches out the player for anybody using 1.15

### ISSUE THREAD

**Issue by grandpablue** [Lord-of-the-Craft/tracker#149]
**Issue**
If you're using 1.16 and repeatedly shift/attempt to sit on a slab/chair etc. while near players using 1.15 there is a visual glitch - the players using 1.15 will see you constantly sitting on the slab you were shifting on even if you are no longer sitting on the chair (you can get up, move around, pvp, etc. and the players using 1.15 will still see you sitting). The glitch breaks if the 1.16 player relogs or interacts with a boat or another slab.

**Ticket refence number:**
RTS-64323
For reference, what I, the 1.15 player saw
![image](https://user-images.githubusercontent.com/79768296/118384069-e54c4680-b5c8-11eb-9306-ffbbe97512e0.png)
vs. where the 1.16 player actually was (obviously not on the slab)
![image](https://user-images.githubusercontent.com/79768296/118384081-fac17080-b5c8-11eb-9e91-60ee1a8da98a.png)

**Comment by Kowaman** [comment]
Issue with viaversion, won't fix
