### ISSUE TITLE
Standing near a ferry causes it to occur

### ISSUE THREAD

**Issue by CheezzyGarlik** [Lord-of-the-Craft/tracker#150]
**Minecraft Username**
Please input your Minecraft usernameCheezzy_Garlik
**Describe the bug**
Standing on a bot next to the ferry will trigger the ferry function and will tp u when the timer is up, even when not standing on the ferry.
**How did this occur**
trying to find a gap in Norlands defenses because i was bored, and found this glitch while i was around the ferry

**Expected behavior**
IDK it just sortya happened and i was suprised, first thing i did was make a modreq, and i was given the link for filing Aa bug report.

**Screenshots**

**Minecraft version:**
1.16,4

**Additional context**

**Comment by The60th** [comment]
Just an issue with the world guard region not matching the ferry build perfectly
