### ISSUE TITLE
Signs are rendering improperly for 1.16.5 users

### ISSUE THREAD

**Issue by grandpablue** [Lord-of-the-Craft/tracker#153]
**Issue**
Users using 1.16.5 are having issues rendering in signs, armour signs, heads. Problem seems to be fixed if they switch back to 1.15

**Ticket refence number:**
RTS- 65351, 65484

**Comment by Kowaman** [comment]
Issue with 3P viaversion, won't fix. Should be remedied when we move to 1.16
