### ISSUE TITLE
LC allows staff members to copy items from itemframes

### ISSUE THREAD

**Issue by grandpablue** [Lord-of-the-Craft/tracker#154]
**Issue**
If you use your bound key to grab a block while in lc you're able to snag items from an item frame - obviously this is normal, but if it was an edited item you can copy the entire item, signature description and all from an item frame

**Ticket refence number:**
RTS- 65245

**Comment by Kowaman** [comment]
@grandpablue wouldn't the item be locked to the LC inventory? So it's just in your inventory, you can't do anything with it

**Comment by grandpablue** [comment]
@Kowaman realizing that would have required me using more than one braincell at a time - yes, you're right. Shouldn't be intractable past grabbing the item

**Comment by FallenVibe** [comment]
Closing this since it seems to be a general non-issue, lest someone protests later!
