### ISSUE TITLE
Soulbinding lilypads allows infinite use

### ISSUE THREAD

**Issue by grandpablue** [Lord-of-the-Craft/tracker#156]
**Issue**
If you soulbind a lilypad you can place down an infinite amount of them on water. Error telling you that you cannot place the item still comes up but placement is allowed

**Ticket reference number:**
RTS-67170

**Comment by The60th** [comment]
@grandpablue 
Can you reconfirm this still happens now that we are fully on 1.16.5 I remember this from a while ago and it seems like a weird display / desync bug. From what I remember is the lillypads are only on the screen of the player who placed them
