### ISSUE TITLE
[ /persona inv ] wipes items from player inventories when they log back on if used while offline

### ISSUE THREAD

**Issue by grandpablue** [Lord-of-the-Craft/tracker#157]
**Issue**
If a staff member uses [ /persona inv ] to drop something into someone's inventory when they're offline, the item will wipe when they're back online (not sure if this is intended or not I'm just cleaning up some of the tickets AHHH, I also cannot replicate - don't have access to the command)

**Ticket refence number:**
RTS- 66264

**Comment by Kowaman** [comment]
Can this be tested? May have been fixed with 1.16
