### ISSUE TITLE
Fennic Remnants subforum not showing up on the recents tab

### ISSUE THREAD

**Issue by grandpablue** [Lord-of-the-Craft/tracker#165]
**Issue**
If you post something in the Fennic Remnants subforum, the post doesn't want to show up on the list of recent posts. Obviously isn't happening with all the subforums, I tested this on the human page as well but it didn't seem to be an issue, but Ando Alur and Nevaehlen subforums are also having this issue

(I have no clue what project to put this under, not even sure if we document forum bugs here don't kill me)

**Ticket refence number:**
RTS- 68234

**Comment by Kowagirl** [comment]
Any new subforums need to be added to recent. Please contact moderation management for this in the future.
