### ISSUE TITLE
Phosphate Crystals

### ISSUE THREAD

**Issue by OmegaIcarus** [Lord-of-the-Craft/tracker#166]
**Is your feature request related to a problem? If so, please describe.**
I've looked deep into the forums and discovered that phosphate crystals might not be implemented into the current world, while Techlock states that it is. I would like to use these items in a number of IC experiments, but no one (be it a player or staff) has been able to point me in the right direction to find the phosphate crystals. This leads me to assume that they're labelled in universe, but not legitamtely implmented.

**Describe the solution you'd like**
Simple put, add the crystals in. Realisticly, phosphate crystals are found in deep caves or mines, after many years of organic material decomposing and crystalizing there. They can be rather simple to obtain, be it mining or carefully chiseling. I'll leave that up to whoever runs that.

**Additional context**
I'm mostly asking about this since I don't know where else to go with it. I've run into a dead end trying to find phosphate ICly and some staff members and veteran players don't recoginze the term "phosphate crystals" or believe they're implemented, although Techlock states it. If it was purposely removed for whatever reason and won't return, that's all I need to know.

**Comment by FallenVibe** [comment]
Got in contact with OmegaIcarus, the feature seems to be resolved now by ST
