### ISSUE TITLE
Friend request unable to be accepted or denied

### ISSUE THREAD

**Issue by grandpablue** [Lord-of-the-Craft/tracker#167]
**Issue**
tadabug2000 recieved a friend req from byrophite which they're unable to remove. Trying to accept tells them they haven't recieved a req, and trying to deny does the same. Further, byrophite doesn't actually seem to be a mc account so.. sussy

**Ticket refence number:**
RTS- 68294

**Comment by TheRanTan** [comment]
Had no further issues, so closed unless the issue arises from the dead
