### ISSUE TITLE
Vortex Teleportation Bug

### ISSUE THREAD

**Issue by polysemic-mc** [Lord-of-the-Craft/tracker#173]
**Minecraft Username**
Polysemic, reported by bufffsanta ingame

**Describe the bug**
When a player follows certain steps (mining a node a certain amount of times and then breaks a locked block) they get teleported back to their original location.

**How did this occur**
Left clicking on an empty node three times with the correct tool, followed by breaking a locked barrel.

**Expected behavior**
No teleportation should occur.

**Screenshots**
![image](https://user-images.githubusercontent.com/84850872/127137108-080c7961-98e3-4499-8b0f-6e1b29781a69.png)
Gif showing the bug in action:
https://cdn.discordapp.com/attachments/869525883193528320/869528638977085470/better_replay.gif

**Minecraft version:**
1.15.2 

**Additional context**
None

**Comment by FallenVibe** [comment]
After testing - no longer an issue.
