### ISSUE TITLE
Monk bread still thinks it's christmas

### ISSUE THREAD

**Issue by grandpablue** [Lord-of-the-Craft/tracker#174]
**Issue**
Monk bread is still gingerbread. It's August.
(wasn't sure what to put this under so i just threw it to Atlas)

**Ticket refence number:**
RTS- 72252

**Comment by Kowaman** [comment]
Real issue is that the special breads were hard-coded, manually changed whenever needed, but usually forgotten about. Whoever picks this ticket up should add some date mapping for special bread.
