### ISSUE TITLE
Locked doors can be opened with a button

### ISSUE THREAD

**Issue by Gyarmo** [Lord-of-the-Craft/tracker#176]
**Minecraft Username**
GMRO

**Describe the bug**
If you have build perms to place a button, you can open a locked door.

**How did this occur**
Player reported it to me.

**Expected behavior**
Shouldn't open

**Screenshots**

**Minecraft version:**
1.16.5

**Additional context**

**Comment by The60th** [comment]
This can be prevented with /lwc flag redstone on, and enabled with /lwc flag redstone off.
