### ISSUE TITLE
Ridden mobs not respawning in tiles without vortex_ranching flag

### ISSUE THREAD

**Issue by grandpablue** [Lord-of-the-Craft/tracker#179]
**Issue**
![image](https://user-images.githubusercontent.com/79768296/128789694-46b8f450-0be4-4192-ad26-11b130b7f120.png)

**Ticket refence number:**
RTS- 72664

**Comment by FallenVibe** [comment]
Seems to be fixed with vortex removal. No ridable mobs despawned in tiles without the vortex_ranching flag during testing.
