### ISSUE TITLE
Switching personas kicks players from the game

### ISSUE THREAD

**Issue by grandpablue** [Lord-of-the-Craft/tracker#181]
**Issue**
Obviously a post-update bug, has been reported by several players (happened to myself as well), when you use /me to switch players (I believe this is specific to personas that have skins saved) you're kicked from game. When you relog, you're on the new persona, but you're in the spot where you were kicked (i.e, you're in the spot you were on the character you just swapped from, not the spot that the character you just switched to should be in)

**Ticket refence number:**
RTS- 73485

**Comment by grandpablue** [comment]
Additional note: Apparently the server kicks you when you try to just change skins, the kick isn't exclusive to changing to/from personas with skins saved

**Comment by Kowaman** [comment]
Fixed by #ec8bea4

**Comment by Kowaman** [comment]
Fixed by https://github.com/Lord-of-the-Craft/lotc-master-archecore/commit/ec8bea41e5f67f068d1c52fbf8d2ee4f038ea0cd
