### ISSUE TITLE
Server-side skin plugin

### ISSUE THREAD

**Issue by OsoaGitHub** [Lord-of-the-Craft/tracker#184]
**Is your feature request related to a problem? If so, please describe.**
I always find it a hassle to have to swap between my casual skin and my persona skin so often, and switching between personas require a skin change also.

**Describe the solution you'd like**
I think a server-side skin plugin would work really well with LotC. The way I imagine that this would work is that players are able to upload their skins using an application form which are then applied every time they join the game. In the form, you are asked what persona this skin is for and what your Minecraft username is. When switching personas, the plugin checks if there is a skin attached and automatically applies it.

**Additional context**
This looks like a possible plugin for the process: [SkinsRestorer](https://www.spigotmc.org/resources/skinsrestorer.2124/
)

**Comment by WonkManBad** [comment]
This is already a feature with VIP.

**Comment by OsoaGitHub** [comment]
> 
> 
> This is already a feature with VIP.

Damn, didn't notice that.

Still, $100 for saved skins is a too high imo. I'll close this anyway
