### ISSUE TITLE
Fishing rods are uncraftable

### ISSUE THREAD

**Issue by grandpablue** [Lord-of-the-Craft/tracker#185]
**Issue**
Vanilla recipe for fishing rods isn't working, people aren't able to craft them 
![image](https://user-images.githubusercontent.com/79768296/130302515-5465ae57-1300-40d3-bd25-038de294b1de.png)

**Ticket refence number:**
RTS-73608

**Comment by FallenVibe** [comment]
Still cannot craft fishing rods through vanilla method. Moved to terra, though unsure which project is best

**Comment by FallenVibe** [comment]
Implemented with recent update.
