### ISSUE TITLE
pikes, maces, etc need their ability to make paths, etc. disabled

### ISSUE THREAD

**Issue by grandpablue** [Lord-of-the-Craft/tracker#188]
**Issue**
![image](https://user-images.githubusercontent.com/79768296/131234389-13b15fb5-8859-44ca-a9a0-7d2f8e9622ea.png)

**Ticket refence number:**
RTS-73114

**Comment by FallenVibe** [comment]
Confirmed with all surge weapons currently.

**Comment by The60th** [comment]
Will track in next surge patch
