### ISSUE TITLE
Item Disappears in offhand

### ISSUE THREAD

**Issue by Burnsalan20** [Lord-of-the-Craft/tracker#191]
**Minecraft Username**
Creator_Alan

**Describe the bug**
Item disappears in offhand if you are holding a 2 handed weapon in your main hand. It seems to happen if you put the whole stack in your offhand. If you only put half of the stack in your offhand, it will simply return the items to the rest of the stack in your inventory. Else it will just delete the whole stack.

**How did this occur**
I was holding my 2 Warhammer mainhand and I put my entire stack of iron ore into my offhand. I then closed the inventory and it deleted the stack completely. I then tried it a few more times by placing only a few items of my stacks into the offhand as well as putting whole stacks. The few items were returned to their original stacks, while the whole stacks were always deleted.

**Expected behavior**
I thought I was holding my regular pickaxe, but turns out I was holding my Warhammer. I expected the items to at least return to my inventory or drop to the ground but neither of these things happened. My iron is gone. Luckily it was only 20 ores.

**Screenshots**
N/A

**Minecraft version:**
1.16.5

**Additional context**
N/A

**Comment by The60th** [comment]
Will look into this week, think I know the cause just need to do some testing to confirm.

**Comment by Burnsalan20** [comment]
Thanks :)
