### ISSUE TITLE
Request: /cmodify for groups of people

### ISSUE THREAD

**Issue by FallenVibe** [Lord-of-the-Craft/tracker#195]
**Issue**
Not issue, feature request.

/cmodify currently allows for adding someone to citizen doors. /cpersist allows to add 1 person to multiple doors or chests. Request is for adding a group of people to a door at once to allow for QoL of Settlements.

**Ticket refence number:**
RTS- 74065

**Comment by The60th** [comment]
This is already supported in lwc. You just provide a list of players with the cmodify command then do /cpersist afters
Example:
/cmodify the60th llir mickaelhz 
/cpersist
Then go smack doors

Or to add players as admins put an @ in front of their name.
/cmodify @the60th @mickaelhz llir
/cpersist
This would add the60th and mickaelhz as admin and llir as a standard user to any lock you click.

**Comment by FallenVibe** [comment]
Perfect, I wasn't aware of that so I've reached out to the person that made the ticket to make them aware.

You can go ahead and lock or close as you see fit.

**Comment by The60th** [comment]
+1
