### ISSUE TITLE
Taking damage when going DOWN an elevator sign

### ISSUE THREAD

**Issue by Chronicsss** [Lord-of-the-Craft/tracker#199]
**Issue**
Whenever you take an elevator sign down it makes you take damage randomly. I believe what is happening is it is calculating the damage that would have been taken if you fell from that height.

**Ticket refence number:**
RTS-76397

**Comment by The60th** [comment]
@Kowaman  tagging you on this.
Does craftbook fire an event when it moves players via signs? We could make some sort of list that prevents their first instance of fall damage after interacting with a sign for x seconds

**Comment by The60th** [comment]
Fix work in progress by myself
