### ISSUE TITLE
Vortex Glitch(nodes)- Found 11/24/2020

### ISSUE THREAD

**Issue by DesiredBreakfast** [Lord-of-the-Craft/tracker#20]
MC Names of all involved
Kholibrii
Description
If you mine a node and then click it after the "mined" texture(bedrock) appears the original texture will flash before returning to the "mined" appearence. Ex: You mine a copper node, then click it again before it regenerates it will flash the gold block for a few ticks before returning to the "mined" texture
Date of occurrence
11/24/2020
In-game specifications
It seems to happen to every single type of node present in the tutorial
Steps to Reproduce

Step 1: Harvest a node
Step 2: Click the node a second time after Harvesting 
Step 3: N/A
Step 4 N/A
Expected Behavior
A message in chat saying the node is not ready to be harvested again
Actual Behavior
A message in chat accompanied by the flashing of the resource on the screen for a few ticks
Additional Information
N/A
Error Message
N/A

**Comment by Nickrocky** [comment]
This is a symptom of us sending a packet to make the block appear different, the main issue is that when you right click it updates the state of the block before the server corrects it. There is no way to fix this bug without upping the number of times we update the block in a second for that packet, so this has got to be a wontfix
