### ISSUE TITLE
/edit roleplay can be infinitely stacked on any item, without a way to remove it

### ISSUE THREAD

**Issue by FallenVibe** [Lord-of-the-Craft/tracker#204]
**Issue**
Using /edit roleplay on an item can be done indefinitely(?), and theres no way to remove the tag once its happened.

Minor issue, but another case to show just how broken it is currently.

**Ticket refence number:**
RTS- N/A

![image](https://user-images.githubusercontent.com/48634310/134528538-81e7d21d-f098-4dff-a00e-b434cac35ff2.png)

**Comment by The60th** [comment]
Fix work in progress by myself
