### ISSUE TITLE
Boars spawning in as zombie pigmen covereing spots with fire

### ISSUE THREAD

**Issue by grandpablue** [Lord-of-the-Craft/tracker#206]
**Issue**
Boars are spawning in as pigmen (pretty sure this isn't news), but there was one spawn location that was found that is covered in flames (see screenshots)
![image](https://user-images.githubusercontent.com/79768296/135514751-a147c434-f04b-4d60-bf4b-bfc6c347ba12.png)
![image](https://user-images.githubusercontent.com/79768296/135514761-480daf0f-4008-43ad-aa17-635de9caddc4.png)

**Ticket refence number:**
RTS- 77495

**Comment by Kowaman** [comment]
No new ones are spawning, this is leftover from 1.15. This shouldn't cause fire unless, can you investigate with Omni? I'm pretty sure pigmen don't ignite, and fire spread should be globally disabled on the `__global__` region

**Comment by The60th** [comment]
Pretty sure I've been by there before and that far was just there, has nothing to do with boar/pigmen
