### ISSUE TITLE
Using horses kicks players with a "you are sending too many packets" message

### ISSUE THREAD

**Issue by grandpablue** [Lord-of-the-Craft/tracker#207]
**Issue**
Tested this, thought it may be speed-related but I wasn't kicked when I was running about, wasn't kicked until I afked for a moment and was just sitting on the horse. You're sent a "you are sending too many packets" kick message
(not sure if this should be under surge or not)
**Ticket refence number:**
RTS- 77881

**Comment by The60th** [comment]
Minecraft client issue
