### ISSUE TITLE
Switching personas duplicates/deletes inventory

### ISSUE THREAD

**Issue by FallenVibe** [Lord-of-the-Craft/tracker#208]
**Issue**
A mod reports that after switching personas from their druid to their ghost, their whole inventory from their druid was duplicated on their ghost.

They were in vanish at the time of switching, though it's unsure if that was the cause.

**Ticket refence number:**
RTS- 77525
![image](https://user-images.githubusercontent.com/48634310/135800642-ab13064c-990e-4c37-b690-a062571976b1.png)

**Comment by Kowaman** [comment]
This occasionally pops up, along with random wipes, not sure the root cause

**Comment by FallenVibe** [comment]
This bug has now been confirmed! Has to do with Limited Creative.

Steps to replicate:
Step 1: Go into LC on a persona
Step 2: Swap personas
Step 3: Exit LC

The inventory from the first persona will now be duplicated on the second persona, wiping the inventory of the second persona.. Armor or anything worn is also duplicated.

Found from RTS 82426:
![image](https://user-images.githubusercontent.com/48634310/142474118-f5906d89-328c-41f8-bfba-cc09e2cd0496.png)
