### ISSUE TITLE
Roleplay items doing PVP damage

### ISSUE THREAD

**Issue by chenn04** [Lord-of-the-Craft/tracker#209]
**Issue**
Items that are marked as /edit roleplay seem to be doing health damage on players, which is not supposed to happen (as far as I know). 
![image](https://user-images.githubusercontent.com/90203965/136881034-d481cb57-229e-4b16-9a5f-26dcb402d1e5.png)
As referenced in the image, the weapon took durability after hitting and inflicting damage on someone.

**Ticket refence number:**
RTS-78793

**Comment by The60th** [comment]
Will be fixed soon working on a patch for itemedit that will fix /edit roleplay
Currently the roleplay tag is basically non functional

**Comment by The60th** [comment]
Fix work in progress by myself
