### ISSUE TITLE
Tools with Roleplay Item tag being usable and not loosing durability

### ISSUE THREAD

**Issue by sinjanko** [Lord-of-the-Craft/tracker#210]
**Minecraft Username**
sinjanko

**Describe the bug**
A tool with Roleplay Item tag added to it can still be used as a tool to its intended purpose without it loosing any durability.

**How did this occur**
I was collecting potatoes with a stone hoe that had the Roleplay Item tag. The hoe did not loose any durability. Testing this out with a wooden pickaxe and iron ended up with the same results. 

**Expected behavior**
I expected the tool to either not be able to gather anything, or it to loose durability. Instead it gathered the materials without loosing any durability.

**Screenshots**
---

**Minecraft version:**
1.16.5

**Additional context**
---

**Comment by FallenVibe** [comment]
Thank you for submitting the bug report. We are currently aware of this issue, among many others, involving the /edit roleplay command. 

With the devs actively working to fix this, I'm going to close out this ticket.
