### ISSUE TITLE
/menu deletes items

### ISSUE THREAD

**Issue by FallenVibe** [Lord-of-the-Craft/tracker#213]
**Issue**
Doing /menu and then Shift + Right Clicking an item sends it into the menu. Once you exit out of the menu, they are deleted.

![image](https://user-images.githubusercontent.com/48634310/139343714-66665873-7e83-4a4c-a6c3-95d80438bdd4.png)

**Ticket refence number:**
RTS- 80287

**Comment by The60th** [comment]
Tythan issue, fix WIP by myself
