### ISSUE TITLE
'[Click for more info]' gives no info 

### ISSUE THREAD

**Issue by AlexMagus** [Lord-of-the-Craft/tracker#214]
**Minecraft Username**
AlexMagus

**Describe the bug**
Clicking on '[Click for more info]' in the text that pops when you you type /persona profession or /persona skill does nothing.

**How did this occur**
Do /persona skill and attempt to click on the grey text.

**Expected behavior**
I expected a list of professions, instead I got nothing!!!!!!

**Screenshots**
![image](https://user-images.githubusercontent.com/76129712/139488531-cb279ffd-b99d-410b-84f3-c7167567f7ca.png)

**Minecraft version:**
1.16.5

**Additional context**
None

**Comment by FallenVibe** [comment]
Thanks for submitting the bug report.

I believe this is just a leftover artifact from an old plugin. It's currently working as intended since professions are currently disabled.
