### ISSUE TITLE
/heads shop deletes item and shows it in shop for everyone

### ISSUE THREAD

**Issue by FallenVibe** [Lord-of-the-Craft/tracker#218]
**Issue**
Doing /heads shop and Shift + Right Clicking an item in your inventory puts the item into the menu. The item also gets deleted.
Everyone is able to see what is put into this menu, though it only lasts until restart.

![image](https://user-images.githubusercontent.com/48634310/141670424-f7d3e491-d573-41e6-97e0-53ce92e8add3.png)

I assume it's tied with #213 

**Ticket refence number:**
RTS- 82098
![image](https://user-images.githubusercontent.com/48634310/141670457-9adc72a3-fce2-4d1e-a7f5-8721b8f314f4.png)

**Comment by The60th** [comment]
Tythan issue fix is a work in progress by myself
