### ISSUE TITLE
/vote milestone wipes inventory

### ISSUE THREAD

**Issue by FallenVibe** [Lord-of-the-Craft/tracker#219]
**Issue**
A user who used /vote milestone had the interface pop up but everything was blank. Upon exiting, their entire inventory was wiped.

The issue doesn't seem to be client side, and persisted after a restart of their client. Happened while the server was under LOW load.
They had not just switched personas to one that had been wiped with server crash, not related to the server crash where people had their inventories wiped. After some testing, cannot replicate the bug.

![image](https://user-images.githubusercontent.com/48634310/141771620-41f0e3f1-b875-4bab-b0eb-7b3121bb16f4.png)

**Ticket refence number:**
RTS- 82284
![image](https://user-images.githubusercontent.com/48634310/141771486-bf6762a6-fe9a-44d3-bef8-828d1f4ebc2e.png)

**Comment by FallenVibe** [comment]
This has happened again with another person.

RTS 89730
![image](https://user-images.githubusercontent.com/48634310/151226976-5db6af14-5cb7-4aad-bf94-3f734be1e069.png)

**Comment by Kowaman** [comment]
This happens occasionally due to a bug in Obelisk Menus, the legacy framework that drives Vegas. This should be resolved when the port of Vegas to Tythan is complete.
