### ISSUE TITLE
Molten Bucket Placement Visual Bug

### ISSUE THREAD

**Issue by CloakandDagger2011** [Lord-of-the-Craft/tracker#22]
MC Names of all involved
CloakandDagger

Description
When placing a bucket full of "molten ore" onto water within a protected area, the lava can spawn at the bottom of the water, replacing whatever block was there without being extinguished. Could be just a visual glitch, not sure, and cant tell with damage turned off.

Date of occurance
11/24/2020

In game specifications
Placed a bucket filled with molten ore into the water across from the alloy smelter. Specifically i remember "jumping" into the water at the same time I placed it.

Steps to Reproduce 
*have not been able to reproduce. The below steps are theorized

Step 1 Obtain a bucket of molten ore.
Step 2 Place into water, attempt to place while falling, jumping, and or under the water.
Step 3 Obtain expected ingots. Lava stays under water.
Step 4

Expected Behavior
Ingots returned to inventory, lava extinguished/vanishes

Actual Behavior
Lava stays and becomes a permanent* block.

Additional Information
I was able to scoop up the lava after it was placed down by using a bucket.
I am unable to verify if the lava replaced the block that was at the bottom. Or if it was just the only hole in that small pond.

I accidentally wiped the ss I had when i copied over the bug report format... oops lol, If I'm able to replicate it ill add it onto this post.
Error Message
N/A

**Comment by CloakandDagger2011** [comment]
![lava](https://user-images.githubusercontent.com/74980787/100132016-d45d1c80-2e52-11eb-8c43-4b7965ea3d65.png)

**Comment by MCVDK** [comment]
After a couple of attempts with falling from the sky -- jumping in place -- running past with the bucket placement: none of them left the visual issue as presented here.
