### ISSUE TITLE
Switching from lc bug wipes inventory

### ISSUE THREAD

**Issue by chenn04** [Lord-of-the-Craft/tracker#220]
**Issue**
There seems to be a bug for staff who switch in and out of LC to be losing their inventories.

**Ticket refence number:**
RTS-83187
![image](https://user-images.githubusercontent.com/90203965/143494702-972dc980-16cf-4eaa-8a38-a1986c87fbc9.png)

**Comment by FallenVibe** [comment]
duplicate of #208
