### ISSUE TITLE
Feature Request: /friend commands shortened to be /f

### ISSUE THREAD

**Issue by FallenVibe** [Lord-of-the-Craft/tracker#221]
**Issue**
Feature Request:
Shorten the /friend command to accept /f as replacement
![image](https://user-images.githubusercontent.com/48634310/145692183-facccc23-2667-4e67-8b1d-9614078ca7fe.png)

**Ticket refence number:**
RTS- 84790

**Comment by Kowaman** [comment]
Third party: Party and Friends
