### ISSUE TITLE
Switching persona teleported player

### ISSUE THREAD

**Issue by FallenVibe** [Lord-of-the-Craft/tracker#222]
**Issue**
A player switched personas from his second persona slot to his third. Instead of taking to where his third was, it teleported him to where the second was.

![image](https://user-images.githubusercontent.com/48634310/145804965-a4f3fc09-71b4-4273-9fb7-cf0bb18249de.png)

After testing, cannot figure out a way to replicate.

**Ticket refence number:**
RTS-85161

**Comment by aiden0023** [comment]
I know this happened to North too, he was telling me last night. I could take a look at it after my finals this week.
