### ISSUE TITLE
Offline tp should be made for logged out players

### ISSUE THREAD

**Issue by chenn04** [Lord-of-the-Craft/tracker#224]
**Issue**
When players log out in places they aren't supposed to, there is no command that is able to teleport them back while offline.

![image](https://user-images.githubusercontent.com/90203965/147626838-c385a9b9-5c4d-4f98-82ff-7386924c1ecf.png)

**Ticket refence number:**
RTS-86306

**Comment by aiden0023** [comment]
But why.
