### ISSUE TITLE
Bugged drake's tail node

### ISSUE THREAD

**Issue by chenn04** [Lord-of-the-Craft/tracker#225]
**Issue**
A drake's tail node went on cooldown when it wasn't able to be harvested.
![image](https://user-images.githubusercontent.com/90203965/147835778-5eb67596-c674-4fc1-8403-e22c709997e6.png)
![image](https://user-images.githubusercontent.com/90203965/147835779-be34bbba-5f74-493b-8b22-dccbac99d5a6.png)

**Ticket refence number:**
RTS-87169

**Comment by FallenVibe** [comment]
I believe this is a WT or Admin issue.
