### ISSUE TITLE
Soulbound items can be used on nodes, draining durability.

### ISSUE THREAD

**Issue by FallenVibe** [Lord-of-the-Craft/tracker#226]
**Issue**
Soulbound items can be used to right-click harvest nodes, thus draining their durability.

**Ticket refence number:**
RTS- 85402
![image](https://user-images.githubusercontent.com/48634310/148647028-8ba6501d-29fa-4412-9916-badf81c4a8e2.png)

**Comment by The60th** [comment]
Needs a check in terra to look for soul bind data.

**Comment by aiden0023** [comment]
> Needs a check in terra to look for soul bind data.

I can do that if you haven't fixed this yet, pretty simple check.
