### ISSUE TITLE
Inventory replaced by another character

### ISSUE THREAD

**Issue by chenn04** [Lord-of-the-Craft/tracker#228]
**Issue**
There is a bug where switching personas copies the inventory from that persona over to the next one.
![image](https://user-images.githubusercontent.com/90203965/150863177-0161609a-e190-41a3-a5ac-4444eb178ec1.png)

**Ticket refence number:**
RTS-89737

**Comment by FallenVibe** [comment]
This happened during an unexpected server crash/restart where a small number of inventories got messed up. The RTS ticket should've stayed up for @grandpablue to try to take care of. Not necessarily a bug that needs fixed.

**Comment by aiden0023** [comment]
> This happened during an unexpected server crash/restart where a small number of inventories got messed up. The RTS ticket should've stayed up for @grandpablue to try to take care of. Not necessarily a bug that needs fixed.

I'm gonna close this then, going through the issue tracker to clean it up right now.
