### ISSUE TITLE
Interesting Ghast sound bug with AH

### ISSUE THREAD

**Issue by FallenVibe** [Lord-of-the-Craft/tracker#229]
**Issue**
Player claims Auction House NPC randomly gives the sound of a Ghast while interacting.

I spammed a couple different auction houses and couldn't get it to happen to me. Borderline a feature, but figure it's best to have it listed.

**Ticket refence number:**
RTS- 89282
![image](https://user-images.githubusercontent.com/48634310/151225327-85b2bf52-5c94-4ec7-85a5-bbad5b2bb24c.png)

**Comment by Kowaman** [comment]
Not a bug
