### ISSUE TITLE
Vortex - EXP Bar Glitch

### ISSUE THREAD

**Issue by gusanoarentonio** [Lord-of-the-Craft/tracker#23]
**MC Names of all involved**
gusanoarentonio

**Description**
EXP from vanilla furnace adds to the EXP (Energy Bar) in Vortex. This is only a visual glitch, but a glitch nevertheless.

**Date of occurance**
25/11/2020

**In game specifications**
Smelted 12 glass, picked up the EXP from it. The EXP took my bar from 100 to 101, which would imply that I have 101 Vortex Energy rather than the 100 I actually have. This does not give me more Nexus energy, merely the visual that I do.

**Steps to Reproduce**
1: Put anything smeltable in a furnace
2: Wait for it to smelt
3: Take it out of the furnace
4: Get EXP from it
5: Watch it fill up your bar

**Expected Behavior**
It should not have filled my bar from 100 to 101.

**Actual Behavior**
It filled my bar from 100 to 101.

**Additional Information**
I am not sure how frequently this occurs, as some of my friends have said it did not occur to them.
![image](https://user-images.githubusercontent.com/72073071/100243143-de0b8080-2f35-11eb-8f95-7b0c28662d79.png)

**Comment by CommissarVoop** [comment]
Ahm this is not a vortex glitch, i have seen this happen on ArcheCore aka the persona plugin.
