### ISSUE TITLE
Netherwart disappearing/unusable

### ISSUE THREAD

**Issue by FallenVibe** [Lord-of-the-Craft/tracker#230]
**Issue**
Netherwart harvested from the nodes disappear upon interaction with other inventories like a crafting bench or chest.

It also disappears if you drop it and try to pick it up.

Related to the closed issue #205, but doesn't seem to be fixed.

**Ticket refence number:**
RTS-
89505
![image](https://user-images.githubusercontent.com/48634310/151229578-a105fe69-2186-4ad3-b8a4-dbeb4d02a91a.png)

89451
![image](https://user-images.githubusercontent.com/48634310/151229609-6443a0ee-2bac-4841-b7c9-abe84a99decb.png)

**Comment by The60th** [comment]
@Kowaman  I think there is a plugin that handles a blacklist of items, netherwarts, enchanting tables, brewing stands etc? I assume this just just getting caught in that filter.

Seems like just something we need to check and see if its fine for players to have these items.
