### ISSUE TITLE
Allow dual-wield of Surge weapons, but remove PvP functionality

### ISSUE THREAD

**Issue by FallenVibe** [Lord-of-the-Craft/tracker#244]
**Issue**
Feature request.

Allow for dual wielding of Surge items by taking away their PvP uses.
See below

**Ticket refence number:**
RTS- 93811
![image](https://user-images.githubusercontent.com/48634310/156070112-66b7c471-2489-4c81-873b-6e48d2842eae.png)

**Comment by Kowaman** [comment]
@The60th Basically the give nerfed command I think, thoughts?

**Comment by The60th** [comment]
Should be handled by training swords, no? @Kowaman

**Comment by The60th** [comment]
This is complete.
