### ISSUE TITLE
Tool/Node switching bug

### ISSUE THREAD

**Issue by iMattyz** [Lord-of-the-Craft/tracker#25]
**MC Names of all involved**
iMattyz
**Description**
Tools switch when they shouldn't.
**Date of occurance**
29/11/20
**In game specifications**
???
**Steps to Reproduce**

    Step 1 - Get stone pickaxe and copper pickaxe (or other superior pickaxe) in inventory
    Step 2 - Mine node with stone pickaxe
    Step 3 - You will instantly be switched from the stone pickaxe to the higher quality pickaxe.

**Expected Behavior**
Not switched
**Actual Behavior**
Switched

**Comment by Kowaman** [comment]
This is intentional, and will only change within your hotbar.
