### ISSUE TITLE
Aeso: Regenerating TNT

### ISSUE THREAD

**Issue by Apothoc** [Lord-of-the-Craft/tracker#252]
I need to work on making some TNT that work.

**Comment by Kowaman** [comment]
For details: This should allow for TNT to be placed and detonate, destroying "non-data" blocks temporarily and then rolling back. This may see implementations in events, raids, or wars, though that has yet to be decided. It should ignore "data blocks" like chests, doors, and item frames, as we don't want issues with LWC or items being lost. Signs can be affected but appropriate precautions will need to be taken to assure we do not lose the content. Further precautions need to be taken for support for restarts and potentially crashes.
