### ISSUE TITLE
Player Skin NPCs

### ISSUE THREAD

**Issue by Kowaman** [Lord-of-the-Craft/tracker#254]
We used to have NPCs as armor stands disguised with LibsDisguises, though upstream changes caused extreme lag and the plugin was changed to use Villagers.

A fix was started using the packet-based [NPCLib](https://github.com/JitseB/NPCLib/) by JitseB, but it lacked features needed at the time, since the the project has been abaondoned.

A new solution is needed - perhaps LibsDisguise has been fixed the lag issue - research is needed on if this is the case, or preferably another packet-based solution as the disguising was hacky. One promising library is [NPC-Lib](https://github.com/juliarn/NPC-Lib) by juliarn which appears to be actively maintained (at least up to 1.18).

**Comment by The60th** [comment]
In progress. Goal to be completed and deployed by 6/12
