### ISSUE TITLE
Book plugin no longer working.

### ISSUE THREAD

**Issue by SacredSource** [Lord-of-the-Craft/tracker#256]
**Minecraft Username**
SacredSource

**Describe the bug**
The book plugin is no longer working. I am not familiar with the code, so I do not know what specifically broke.
https://wiki.lordofthecraft.net/index.php?title=Books

**How did this occur**
Use a minecraft & quil and try to paste in any of the liens shown in the link above.

**Expected behavior**
I expected the text in the book to change to a different font after pasting it in. I was unable to paste it in.

**Screenshots**
N/A

**Minecraft version:**
1.16 and 1.17

**Additional context**
N/A

**Comment by Kowagirl** [comment]
Updated the wiki
