### ISSUE TITLE
/friend remove [IGN] not working for some Usernames

### ISSUE THREAD

**Issue by HobbitForHire** [Lord-of-the-Craft/tracker#257]
HobbitForHire - Impacted user is BlueFoxes

[/friend remove Poppycon] is not working for user. They are receiving the message 'The player **Poppycon** is not online or you are not his friend.
Testing this, the online side of things doesn't appear to be an issue as I was able to unfriend another user that had not been online for some time. It seems to be the user's name more than anything

User was clearing their friend list. Other friends were removed just fine

Friend removal and confirmation note

![CFA6F064-8029-42B8-91A0-7948BC40D420](https://user-images.githubusercontent.com/53019875/164998547-1b058674-458f-4e65-8c05-10511dbcc911.jpg)
![IMG_3623](https://user-images.githubusercontent.com/53019875/164998549-b9d6ba9a-644a-4ac1-b940-d08ac6002013.jpg)
![371B477B-DEAA-439D-9934-25C48352E002](https://user-images.githubusercontent.com/53019875/164998507-adaea67b-11f2-4f2b-9f86-b63f1fa1c0e6.jpg)
![23413290-E355-4C2D-B227-EF9EF9C176D4](https://user-images.githubusercontent.com/53019875/164998525-2a8d2fc8-af22-4bca-95b4-be6686ba0da1.jpg)
![Capture](https://user-images.githubusercontent.com/53019875/164998546-31b8e09f-e1aa-4355-93dd-3f32407c270a.PNG)

1.16

Unable to replicate personally

Req 99075 if that's of any help

**Comment by aiden0023** [comment]
Maybe something with Poppycon being offline for so long? I'll look into it.
