### ISSUE TITLE
Dropping Item Bug

### ISSUE THREAD

**Issue by AlienPebbles** [Lord-of-the-Craft/tracker#266]
**Minecraft Username**
Please input your Minecraft username
BlueFoxes

**Describe the bug**
When dropping an item, it doesn’t show the item being dropped. But the item IS dropped. 
example: I give our cookies to everyone I see. More often than not, when I drop a cookie. It doesn’t show it happening and I can’t tell if the person picks up the item. But the amount of cookies in my inventory still goes down.

**How did this occur**
Please explain what lead to this bug, and how we might reproduce it for testing.
Stated in last paragraph.

**Expected behavior**
A clear and concise description of what you expected vs what actually occurred.
All I’m asking is that this be looked into. Thank you!

**Screenshots**
Can’t really be shown through screenshots

**Minecraft version:**
What Minecraft version are you using
1.16.5 

**Additional context**
It happens with other items besides cookies, too.

**Comment by riroo** [comment]
Hi! Let's start with I'm not a Tech team member, but I think I can guess the issue here. Are you using a version of optifine if so which one?

**Comment by AlienPebbles** [comment]
Hello! And yes I am. I’m using 1.16.5-optifine_hd_u_g7

**Comment by FallenVibe** [comment]
PM me on discord, Hermit Jack#5398 so I can help you out quicker

**Comment by Kowaman** [comment]
Client side, closed.

**Comment by AlienPebbles** [comment]
Hello! And yes I am. I’m using 1.16.5-optifine_hd_u_g7
