### ISSUE TITLE
Leave sit when use Item.

### ISSUE THREAD

**Issue by SriFoo** [Lord-of-the-Craft/tracker#269]
SriFoo

Whenever an item is used, such as a book, food, or anything else, sit is disabled.

This is true, for /sit, for slabs, and for stairs.

I have not found any expectations

Happily Sitting.
![image](https://user-images.githubusercontent.com/106494875/170893666-248628bd-34b0-414f-aca4-b94fd90af2ef.png)
Eats some Bread.
![image](https://user-images.githubusercontent.com/106494875/170893683-68872f6d-7541-45dd-8248-46e71bcc36ff.png)
No longer sitting.

Version: 1.17.2

**Comment by FallenVibe** [comment]
Thanks for the bug report. The server is made for 1.16.5, so if you use that version you will not get this issue.
