### ISSUE TITLE
Kelp in farming improvement tiles does not grow

### ISSUE THREAD

**Issue by Hobolympic** [Lord-of-the-Craft/tracker#27]
**MC Names of all involved**
Hobolympic

**Description**
Kelp does not grow in tiles with farming improvement. Harvested once, never grew back.

**Date of occurance:** 
12/01-20

**In game specifications:**
There's a lake in Urguan capital tile meant for kelp farming (dunhiem subregion). It was fully grown upon launch, and harvested the same day. It never grew back, even after 4 days and times of low server load. All other crops seem to grow nicely, with kelp being the odd exception.

**Steps to Reproduce**

- Step 1: Plop down kelp in a lake with room to grow, in a regioned tile that has farming enabled (tile_75 is the one in question, though this might be a global issue)

- Step 2: Simply wait for it to grow. 

**Expected Behavior**: Kelp should grow

**Actual Behavior** Kelp doesn't grow

**Additional Information**
Again, not sure if this issue also applies to other regions. Also tried to replant the kelp, no success.

**Comment by Kowaman** [comment]
Please request the moderation team to set the 'vine-growth' flag to 'allow'
