### ISSUE TITLE
2 person horses allows more than 2 at once

### ISSUE THREAD

**Issue by FallenVibe** [Lord-of-the-Craft/tracker#270]
**Issue**
Horses can hold multiple people at once, like 3 or 4 on the back of a horse.

**Ticket refence number:**
RTS- 102106
![image](https://user-images.githubusercontent.com/48634310/171037362-a8af29ac-7ed6-4510-9f6f-21e6cb892461.png)

**Comment by The60th** [comment]
Fixed waiting to deploy
