### ISSUE TITLE
You mount your horse when trying to put it away if cooldown isn't over.

### ISSUE THREAD

**Issue by FallenVibe** [Lord-of-the-Craft/tracker#271]
**Issue**
So if you summon your horse, mount it, unmount it, then try to put it away using the whistle while it's still on cooldown then you mount the horse instead.

Step 1: Summon Horse
Step 2: Mount Horse
Step 3: Unmount Horse
Step 4: Attempt to put horse away during cooldown with the horse whistle in hand

If you just summon and then put away your horse without mounting it, then there is no issue.

I thought this was intentional, but I've gotten a few DMs saying that it's annoying and seems unintentional.
**Ticket refence number:**
RTS- N/A

**Comment by The60th** [comment]
Fixed waiting for deployment
