### ISSUE TITLE
Bee Eggs are not spawning bees.

### ISSUE THREAD

**Issue by Hobolympic** [Lord-of-the-Craft/tracker#28]
**MC Names of all involved**
Hobolympic
**Description**
Right-clicking with a bee egg won't spawn a bee.
**Date of occurance**
12/01-20
**In game specifications**
Bought two bee eggs from northern hub shop. Left-clicking won't spawn them, but the eggs don't disappear. Tried spawning them with a dispenser, and both eggs disappeared with no spawned bees.
**Steps to Reproduce**

- Step 1: Right click with bee egg in hand

**Expected Behavior** A bee is spawned, egg disappears

**Actual Behavior** No bee is spawned, egg doesn't disappear. 

**Additional Information**
n/a
**Error Message**
n/a

**Comment by Kowaman** [comment]
Not a bug. Bees are disabled. I removed the shops at hubs a few hours ago.
