### ISSUE TITLE
/edit desc --newline Bug

### ISSUE THREAD

**Issue by MeteorDragon9** [Lord-of-the-Craft/tracker#283]
**Minecraft Username**
Meteor__Dragon

**Describe the bug**
Doing /edit desc --newline simply types "--newline" rather than making a newline

**How did this occur**
Hold an item and type /edit desc --newline

**Expected behavior**
What I expected was it to insert a blank line below what's been written on the description like in the past, however it simply wrote "--newline" instead

**Screenshots**
![image](https://user-images.githubusercontent.com/87495727/171941364-4769f152-db3a-4262-ad49-96f8676a5bc5.png)

**Minecraft version:**
1.16.5

**Additional context**
None

**Comment by FallenVibe** [comment]
Thanks for the bug report. The solution is to use "/edit desc -newline" instead of "/edit desc --newline" Basically, you added an extra dash.
