### ISSUE TITLE
/showitem, broken.

### ISSUE THREAD

**Issue by SriFoo** [Lord-of-the-Craft/tracker#284]
SriFoo

When /showitem is used a message appears in chat saying that an unhandled exception occurred. The other player does not see the item.

This can be reproduced by trying to do /showitem to a nearby player.

I expect for the item to appear in a tool tip the the chat of the player who I mention in the command, which when hovered over will display the description of the item.

![image](https://user-images.githubusercontent.com/106494875/171963004-30bc4ef0-1a28-4400-91e4-0ef162c0d1f4.png)

1.17.2 

This problem has occurred with many other people, so the version if irrelevant.

**Comment by FallenVibe** [comment]
Thank you for the github report and /treqs regarding this same issue. We're aware of it and actively working to fix it.
