### ISSUE TITLE
Duping 

### ISSUE THREAD

**Issue by Geminisole** [Lord-of-the-Craft/tracker#29]
This happened to me only with tin and I am not 100% sure whether it was just lag etc. 

But I tried to place a bucket of molten tin into water and at the first attempt it didn’t empty the it. For the second try it did but I got the tin 2x (I think).
Now I’m not fully sure whether this is just me being brain dead but...  better to be safe than sorry.

**Comment by Deer2underscores** [comment]
I was not able to replicate this issue. If you find a way to replicate this issue please make a new comment with the proper format on the DevTracker.
