### ISSUE TITLE
Aviary Plugin Bug

### ISSUE THREAD

**Issue by Reznc** [Lord-of-the-Craft/tracker#295]
**Minecraft Username**
Reznc

**Describe the bug**
I don't know how to describe it other than the error message that showed: "An unhandled exception occurred. Contact a Developer."

**How did this occur**
I had written a letter, signed it, and then intended to send it off to a recipient.

**Expected behavior**
I expected to watch the parrot fly off with my letter.

**Screenshots**
N/A

**Minecraft version:**
1.17.1

**Additional context**
This is the first time the plugin has failed to work for me.

**Comment by FallenVibe** [comment]
We're aware of this issue, and a fix is being worked on. Thank you.
