### ISSUE TITLE
Shop Bug

### ISSUE THREAD

**Issue by PrincessSnowie** [Lord-of-the-Craft/tracker#30]
MC Names of all involved

Description

Date of occurance Recently since Revamp.

In game specifications Basically when I try to sell glowed items through my shop, it displays fine after I use the commands, but when I log off and log back on. It shows the item on display without glow, and says the item is sold out, when I check my shop chest and my bank, it shows all the items still there, and no mina sent to my bank. So it's somehow stopping my shop from selling them.

Steps to Reproduce

Step 1Place item/s with glow in shop chest
Step 2 Set up item to be sold on slab
Step 3Log Off (I usually log off overnight im unsure if it has any difference)
Step 4 Log back on and check item
Expected Behavior
The stall should be selling and displaying my item normally, as its only affecting items with glow on them.
Actual Behavior
The staff glitches saying my shop is out of the items with glow, when they remain in the shop chest.
Additional Information
N/A
Error Message
N/a

**Comment by Deer2underscores** [comment]
Unable to replicate. Is this happening with a specific item or several different types of items?

**Comment by Deer2underscores** [comment]
Happens on server restarts.

**Comment by MCVDK** [comment]
Similar to #76 in relation to the glow effect and #104 in relation to the stock issue.
