### ISSUE TITLE
Lifts do damage to players using them well moving backwards.

### ISSUE THREAD

**Issue by riroo** [Lord-of-the-Craft/tracker#305]
**Minecraft Username**
rdowdy

**Describe the bug**
Lifts down do damage when a player is moving backwards

**How did this occur**
Move backwards (typically by pressing the S key) and use a [Lift Down] that travels a distant more than 5 blocks. Strafing well moving backwards will still mean the player takes damage, but moving forward in any way will stop the effect from happening.

**Expected behavior**
I don't expect to take damage when moving backwards and using a Lift

**Screenshots**
N/A

**Minecraft version:**
1.16.5

**Additional context**
N/A

**Comment by The60th** [comment]
Part of craftbook and not something we currently develop. May take a while to change if possible.
