### ISSUE TITLE
Change lift obstruction rules so it no longer consideres signs.

### ISSUE THREAD

**Issue by riroo** [Lord-of-the-Craft/tracker#306]
**Is your feature request related to a problem? If so, please describe.**
Lifts consider signs an obstruction when considering a safe landing platform. 

**Describe the solution you'd like**
For signs to not be included when lifts check for obstructions so Elevators in 1x1 spaces with multiple floors function and don't require a player to stand outside of them.

**Additional context**
![Screenshot](https://user-images.githubusercontent.com/59296875/173020882-29dcc628-5c45-4c1e-971a-e9f1b88f71cd.png)

This picture shows an Elevator in a 1x1x2 space. It cannot be used for traveling up a floor if the player is actually in the elevator.

**Comment by The60th** [comment]
Part of craftbook and not something we currently develop. May take a while to change if possible.
