### ISSUE TITLE
Change several recipes so they actually provide an amount based on the material amount inputed.

### ISSUE THREAD

**Issue by riroo** [Lord-of-the-Craft/tracker#307]
**Is your feature request related to a problem? If so, please describe.**
It is insanely frustrating how few trapdoors I get for six wooden planks. The pixel measurment suggests I should get 24 Trapdoors from 6 blocks of wood. This is a similar issue with stairs.

**Describe the solution you'd like**
All stair recipes should be changed so the 6 material you input creates 8 stairs. Wooden trapdoors should be changed to get at least 12 from the 6 wood require for the recipe, but at the bare minimum please make it more than two. Bricks are more niche so it's more or less whatever. 

**Additional context**
N/A

**Comment by Kowaman** [comment]
We try to keep most things vanilla as is
