### ISSUE TITLE
Horses do not actually have a cooldown when angered. 

### ISSUE THREAD

**Issue by riroo** [Lord-of-the-Craft/tracker#309]
**Minecraft Username**
rdowdy

**Describe the bug**
When using the /bridle command if you get "The animal seems angered by your previous attempt and will refuse to interact with you for a period of time." you can just continue to use /bridle until it grows a liking to you.

**How did this occur**
Release a horse from a whistle with shift-rightclick and do /bridle. Continue to repeat that cycle until it gets angry at you. Then do /bridle again. There is no cooldown.

**Expected behavior**
For a cooldown preventing me from using /bridle on the same horse even after angered

**Screenshots**
![image](https://user-images.githubusercontent.com/59296875/173026487-2c4ccb91-a213-495a-ad3f-2e28999516ba.png)
This one got made at me twice and still let me tame it on the 3rd try.

**Minecraft version:**
1.16.5

**Additional context**
This has actually been really helpful for making renaming horses not completely terrible since you don't need to worry about the horse getting angered since you can just keep trying until you can rename it.

**Comment by The60th** [comment]
WIll be reworked in the coming weeks
