### ISSUE TITLE
Cows no longer drop leather

### ISSUE THREAD

**Issue by Quavinir** [Lord-of-the-Craft/tracker#31]
MC Names of all involved: Auric_Saint

Description: Cows no longer drop leather.

Date of occurance: 12/4/2020

In game specifications: At Druids Grove, minimum server load, 1.15.2 game version.

Steps to Reproduce:

Step 1: Find a cow
Step 2: Kill a cow with hands.

Expected Behavior: Leather would drop from killing the cow, alongside beef, and a vortex animal hide.

Actual Behavior: Leather does not drop, only a vortex animal hide, and sometimes beef.

Additional Information: None

Error Message: None

**Comment by MCVDK** [comment]
This is intended behaviour for the plugin- you can use animal hide to craft leather and books no longer require leather to craft.
