### ISSUE TITLE
Keep inventory upon death to environment.

### ISSUE THREAD

**Issue by SriFoo** [Lord-of-the-Craft/tracker#314]
While exploring the various maps of LOTC it is a common occurrence to die to some unexpected hole or hazard. This can involve losing all items if that is lava, or a lengthy trip should it be due to fall damage. This basically causes an interruption to the experience. 

I think that any deaths caused by the environment, in unclaimed territory, would not cause the inventory to drop.

I can see how this would be a difficult thing to implement for not much gain, but it would defiantly remove a lot annoyance while exploring the map.

**Comment by FallenVibe** [comment]
I could see this as something like removing fall damage, lava damage, and water damage unless statused for PVP.
