### ISSUE TITLE
Persona based /cmodify

### ISSUE THREAD

**Issue by SriFoo** [Lord-of-the-Craft/tracker#315]
Especially during war having multiple personas, some belonging to different nations can cause a hassle for locked doors and chests. This is because /cmodify adds people to doors universally based on username.

Adding people to doors made on persona rather then player name would be ideal.

I understand that /cmodify is not a plugin made by lotc staff so editing it would be difficult, and making a new plugin would also be difficult. Just putting the idea out there.

**Comment by FallenVibe** [comment]
I've never come across any hassle with locked chests/doors in the manner you state.

In relation to personas and locked chests, something like that already exists. If I remember right, when you go to PK a persona, every chest that persona owns gets removed. Unsure about door locks.

I don't know, maybe something more complex is something to think about, but unsure if it's really needed at this time.

**Comment by SriFoo** [comment]
I was unaware of that, and yeah it is not a big issue for me.
