### ISSUE TITLE
AH Dupe Method

### ISSUE THREAD

**Issue by FallenVibe** [Lord-of-the-Craft/tracker#318]
**Issue**
User claims spamming items onto the AH can duplicate them.

Duplicated items were confirmed to be on AH, but I cannot replicate the bug.

Extra info:
![image](https://user-images.githubusercontent.com/48634310/176026260-367e5942-c824-42b6-8ac4-e5664f6ee925.png)

**Ticket refence number:**
RTS- 103645
![image](https://user-images.githubusercontent.com/48634310/176023981-3de39140-cbc8-4752-93ae-d083ce5d894a.png)

**Comment by Kowagirl** [comment]
AH has been removed as of 9.0
