### ISSUE TITLE
No energy breeding attempt dupes wheat

### ISSUE THREAD

**Issue by Sybbyl0127** [Lord-of-the-Craft/tracker#32]
MC Names of all involved: Sybbyl

Description: When attempting to breed animals that are MCly ready to breed, but you are out of energy and cannot, plugin gives too many wheat back

Date of occurance: 12/5/2020

In game specifications: At Druids Grove, minimum server load, 1.15.2 game version.

Steps to Reproduce:

Step 1: Unsure if large # of animals is necessary, but I have 15+, they were ready but I'm out of energy
Step 2: Spam click with wheat to try and get them all to breed, then wait
Step 3: Plugin tells me I dont have enough energy, but the sheep ate the wheat, when the breeding attempt then subsequently fails, it kept giving me back the wheat and I ended up nearly doubling and then some, the wheat I had on hand

Expected Behavior: Give back the number I had or just consume it, unsure

Actual Behavior: Keeps putting wheat back into my inventory over and over

Additional Information: None

Error Message: None

**Comment by Kowaman** [comment]
Fixed in Vortex 0.2.0
