### ISSUE TITLE
Aviary birds freezing on high load

### ISSUE THREAD

**Issue by FallenVibe** [Lord-of-the-Craft/tracker#322]
**Issue**
I believe the issue was fixed before, but birds on high load are just standing in place again.
![image](https://user-images.githubusercontent.com/48634310/178129820-efb82c50-ce6f-4192-a59f-171207739e37.png)

**Ticket refence number:**
RTS- 105425
![image](https://user-images.githubusercontent.com/48634310/178130030-6296b625-c057-4e7d-b9bf-804f4080b872.png)

**Comment by Kowagirl** [comment]
Fixed some time ago
