### ISSUE TITLE
Random invisible, indestructible armor stands appearing

### ISSUE THREAD

**Issue by FallenVibe** [Lord-of-the-Craft/tracker#324]
**Issue**
Unsure if it's just a staff member trolling, but invisible/indestructible armor stands keep appearing around. I know they can be created using /summon command.

Can be removed with WE using //cut, but otherwise they just stay there forever.
![image](https://user-images.githubusercontent.com/48634310/179005506-a0723751-8946-48db-bd81-c165a2d28fab.png)

Unsure project.
**Ticket refence number:**
RTS- 105388

**Comment by The60th** [comment]
Looking back I think this may be an issue on my end with two-player-horses if something fails to remove the armor stand properly. Will look into this as I've started to see more and more of them show up.

**Comment by Kowagirl** [comment]
Fixed with patch in AtlasModule
