### ISSUE TITLE
Treqs not showing from beta server to main

### ISSUE THREAD

**Issue by Lockages** [Lord-of-the-Craft/tracker#335]
When in the beta server, if /check is run, it shows a separate list of tickets that were only made in the beta server. Aka the main server tickets and beta server tickets don't link into the same group.

Ticket refence number: Self Report

**Comment by Kowagirl** [comment]
Could be argued this was intentional, as beta may have a different version of RTS then main, though this is not a good choice as beta is open. Will copy main DB config and promote directly from dev to main should there be schema changes.
