### ISSUE TITLE
Nani Toggle not censoring some words.

### ISSUE THREAD

**Issue by Lockages** [Lord-of-the-Craft/tracker#343]
Chat swear filter not censoring the word "cumcage", or any word with cum it.

After reluctantly spamming cum over and over again with the toggle on, and getting someone else to do it... seems that the /nani toggle does indeed not block the word cum. Seems to not be a bug and just that the word isn't implemented. Might want to fix that...

Ticket refence number: 117819
RTS-

**Comment by Kowagirl** [comment]
Nani filter is configured by moderation management, contact them for adjustments.
