### ISSUE TITLE
Craftbook

### ISSUE THREAD

**Issue by itdontmatta** [Lord-of-the-Craft/tracker#346]
**Minecraft Username**
itdontmatta

**Describe the bug**
Craftbook gate signs do not work near or below y-level=0

**How did this occur**
Try to place a full iron_bar gate at y-level=0 or below. It will only close partially, or not at all.

**Expected behavior**
I expect the gate to fully open and close. 

**Screenshots**
N/A, I think you know about this already Kowa.

**Minecraft version:**
1.18.2

**Additional context**
Craftbook bridges work. 
It seems like the [X] key mechanism of Craftbook isn't working at all. I've tried at y-level below 0 and above. Might require some further testing.

**Comment by Kowaman** [comment]
Fixed by https://github.com/Lord-of-the-Craft/CraftBook/commit/e1ebf59e1bf4b00393867b560b1fa25592175f5a
