### ISSUE TITLE
Hours played were not reset on map change

### ISSUE THREAD

**Issue by itdontmatta** [Lord-of-the-Craft/tracker#348]
**Issue**
/persona played uses hours played from Almaris and not from Aevos. It is not starting from 0 in the new map. Both fields show the same amount of hours.
![image](https://github.com/Lord-of-the-Craft/tracker/assets/107372304/af17c08d-d013-498e-aef8-c3a50a58aa15)

**Ticket refence number:**
RTS- 125718

**Comment by Kowagirl** [comment]
Fixed by https://github.com/Lord-of-the-Craft/lotc-master-archecore/commit/e8e31341bddfaec173698e9508ecca2603184045
