### ISSUE TITLE
Chest/Furnace UI

### ISSUE THREAD

**Issue by itdontmatta** [Lord-of-the-Craft/tracker#349]
**Issue**
Apparently sometimes when you open a UI (chests, or furnaces), and throw raw iron, coal, or raw goal into it, it is removed from their inventory and unable to be picked up. This may be due to lag or other issues, but personally I haven't had any problem with putting stuff into a UI. 

This might have occurred when the player-connection thread crashed an hour or two after launch.

**Ticket refence number:**
RTS- # 125727

**Comment by Kowagirl** [comment]
Ticket was made prior to my patch for this.
