### ISSUE TITLE
Excess Fleece Bug

### ISSUE THREAD

**Issue by DragonofTaters** [Lord-of-the-Craft/tracker#35]
So I was breeding and shearing sheep to try and gather fleece. While breeding them, I accidentally clicked on the baby sheep with my shears. This gave me a ball of fleece. I clicked again, and it repeated the drop. Using this, I was able to gather several chests filled with fleece. In addition, it did not use up the durability on my shears I had in my hand. Please fix this soon, and also let people know this is a glitch and should not be used, as I was banned and don't want to see other people make the same error in using this system to gather resources.

**Comment by Kowaman** [comment]
This was already patched.
