### ISSUE TITLE
Cloud Temple and Respawning

### ISSUE THREAD

**Issue by itdontmatta** [Lord-of-the-Craft/tracker#350]
**Issue**
Three players made a /treq and described the CT as "not being loaded" and they were brought to spawn. I tried to inquire further, but they stated that the issue is no longer happening.

UPDATE: I followed up and asked where they were taken to - and they were taken to a random field in Aevos. I think it might have been the Multiverse World Spawn for the Aevos map. I once died from fall damage on the Aevos map, and was teleported there. 

**Ticket refence number:**
RTS- #125742 #125743 #125744

**Comment by Kowagirl** [comment]
Fixed by https://github.com/Lord-of-the-Craft/lotc-master-soulstone/pull/7/commits/c42eb797417a92f59feb369f180ef294f42695a7#diff-72256c2c820e11619da267bd69ae20bd174f09a4de6af2719eed7e69c40776e3L311-R311
