### ISSUE TITLE
Herb nodes not stacking

### ISSUE THREAD

**Issue by itdontmatta** [Lord-of-the-Craft/tracker#352]
**Issue**
Herb nodes not stacking. This was reported by a player. I attempted to replicate the issue, and the item stacked for me fine.  

**Ticket refence number:**
RTS- 125899

**Comment by TheRanTan** [comment]
This is an intended feature to separate newly harvested herbs from old ones. I suggest its removal as it is not needed. Herbs may be stacked after a set amount of time
