### ISSUE TITLE
Custom Signs

### ISSUE THREAD

**Issue by itdontmatta** [Lord-of-the-Craft/tracker#353]
**Issue**
Custom sign displays sometimes do not work. I attempted to replicate the issue and I was able to use both dye and glowing ink sac to change the data on a sign without issue. When the player did it, it gave them the following error:

"an unhandled exception occurred, contact a developer"

**Ticket refence number:**
RTS- #125914

**Comment by Adelemphii** [comment]
Fixed on latest build, awaiting update on main.
