### ISSUE TITLE
LWC

### ISSUE THREAD

**Issue by itdontmatta** [Lord-of-the-Craft/tracker#354]
**Minecraft Username**
itdontmatta

**Describe the bug**
When you type /cinfo, it gives you the owner of the lock's UUID instead of their username.

**How did this occur**
Type /cinfo on a lock. I've added an example. "/warp cinfo", and then /cinfo the door in front of you. Delete the warp when done tho :3. The admins and users on the lock come up as usernames. This only happens for the owner of the lock. 

**Expected behavior**
I expect to see a person's username.
What I see instead is a UUID.

**Screenshots**
![image](https://github.com/Lord-of-the-Craft/tracker/assets/107372304/73a29c0b-d4a4-4104-b066-6dd387675d92)

**Minecraft version:**
1.18.2 Feather Client

**Additional context**
N/A

**Comment by Kowaman** [comment]
Placeholder was updated from `%owner%` to `%name%` in the locale file.
