### ISSUE TITLE
Day/Night Cycle

### ISSUE THREAD

**Issue by itdontmatta** [Lord-of-the-Craft/tracker#355]
**Issue**
People are sleeping and messing with the daylight cycle. I know Llir fixed this last night, but I asked around in VC this evening and apparently it is still happening. It is apparently messing with /date, according to the ticket made by Fishy

**Ticket refence number:**
RTS-  #u000893

**Comment by Kowagirl** [comment]
People sleeping isn't messing with `/date`, but it also appears our time of day override is not working.

SIdenote: I did fix the player sleeping %

**Comment by Kowagirl** [comment]
Fixed by https://github.com/Lord-of-the-Craft/lotc-master-archecore/commit/0aa4827723e3f96487870e16c00b888182939515
