### ISSUE TITLE
Cant pick up in a certain area

### ISSUE THREAD

**Issue by itdontmatta** [Lord-of-the-Craft/tracker#356]
**Minecraft Username**
itdontmatta

**Describe the bug**
Some items cant be picked up in certain areas. It started with someone popping and dropping the mina on their persona and dropping their soulstone.

**How did this occur**
See above.

**Expected behavior**
Should be able to pick up the mina and the soulstone?

**Screenshots**
![image](https://github.com/Lord-of-the-Craft/tracker/assets/107372304/f6d81639-7091-4ddc-94fb-415572cb4f15)

**Minecraft version:**
1.18.2

**Additional context**
Really hope this isn't a corrupted chunk -_-
/warp brokenchunk

**Comment by itdontmatta** [comment]
Looks like this was fixed upon server restart. Might require some further investigation (bad thread?)

**Comment by Kowagirl** [comment]
I think this was fixed with the chunk loading changes I did earlier.
