### ISSUE TITLE
Heads are free on the heads shop

### ISSUE THREAD

**Issue by xepphir** [Lord-of-the-Craft/tracker#365]
**Minecraft Username**
xepphir

**Describe the bug**
Apparently the heead shop is free for everyone and people are buying heads in bulk, they even said lthat 20 stacks are in a shop. Perhaps if heads are free there could be a cooldown? to prevent any issues in the future

**How did this occur**
not sure

**Expected behavior**
i am not sure

**Screenshots**
[If applicable, add screenshots to help explain your problem.](https://media.discordapp.net/attachments/427579416261033994/1121560692852535306/2023-06-23_00.01.31.png?width=1202&height=676)

**Minecraft version:**
1.18.2

**Additional context**
a player came to me and dropped a bunch of heads, addressing the issue. Heads were being placed too.
![2023-06-23_00 01 31](https://github.com/Lord-of-the-Craft/tracker/assets/127139814/6d118167-f74b-4e83-b793-e7680140303c)

**Comment by TheRanTan** [comment]
This has been disabled after the initial "Server Setup" period. Working As Intended.
