### ISSUE TITLE
RPSigns' --custom display tag does not work

### ISSUE THREAD

**Issue by Hyperdron** [Lord-of-the-Craft/tracker#366]
**Minecraft Username**
Hyperdron

**Describe the bug**
Attempting to use RPSigns' --custom display tag on an RPSign fails and throws up an unhandled exception.

**How did this occur**
By looking at an RPSign and typing the command '/rpsign display --custom' to try and change the sign's display text.

**Expected behavior**
It used to bring up an anvil GUI where one could write in the text they wanted the sign to have displayed on itself. Now, the command fails and puts the message in chat "Error: an unhandled exception occurred. Contact a developer."

**Screenshots**
N/A (pretty easy to replicate)

**Minecraft version:**
1.18.2 (Fabric)

**Additional context**
All other display tags (--default, --note, --painting, --poster) were tested and worked as intended. Bug has been consistently reproduced by more than one player (Hyperdron and Laurelin so far).

**Comment by Adelemphii** [comment]
Fixed on latest build, awaiting update on main.
