### ISSUE TITLE
Discord Update Broke Nitro Slot

### ISSUE THREAD

**Issue by TimberBuff** [Lord-of-the-Craft/tracker#368]
**Issue**
Players are not receiving the nitro booster slot since the discord update, most likely due to the lack of discriminators on discord accounts now. 

**Ticket refence number:**
RTS- 127695

**Comment by Kowagirl** [comment]
Fixed by https://github.com/Lord-of-the-Craft/lotc-master-freja/commit/281678e2d335affa14c3438f7d657b06a047a153
