### ISSUE TITLE
Dupe from Warclaim

### ISSUE THREAD

**Issue by StripeyIO** [Lord-of-the-Craft/tracker#381]
**Minecraft Username**
SStripe

**Describe the bug**
Items from before i synced my account are on my other persona 

**How did this occur**
I'd assume something with warclaim sync but i do not know

**Expected behavior**
A clear and concise description of what you expected vs what actually occurred.

**Screenshots**

**Minecraft version:**
1.20.1

**Additional context**
I did mess up the restore so i gave the weapons back to my main persona still weird not mad but it synced some items that i'd stored away before the warclaim even began to be prepped about a 1 before the main rally like rp items and other such that i did store and i checked my chest back where i had my stuff and it was all there it as duped

**Comment by StripeyIO** [comment]
Also i do not know if this is normal but my alt persona has same door perms for my main and can access anything my main persona can

**Comment by Kowagirl** [comment]
Warsync plugin has been rewritten since this issue was opened.
