### ISSUE TITLE
Veltz mine is missing copper nodes, redstone, and lapis

### ISSUE THREAD

**Issue by madzyme** [Lord-of-the-Craft/tracker#384]
**_mady07**

**Describe the bug**
Seems that the mine is missing these nodes and only pulling 25 redstone, and lapis instead of each giving 32
**How did this occur**
I cant reproduce this and it doesn't seem to be changed

**Expected behavior**
A clear and concise description of what you expected vs what actually occurred.

**Screenshots**

**Minecraft version:**
18.2

**Additional context**

**Comment by TheRanTan** [comment]
Is this missing nodes or broken nodes?

**Comment by Kowagirl** [comment]
Please make modreqs for node issues
