### ISSUE TITLE
Unable to use mouse button three to copy banners

### ISSUE THREAD

**Issue by madzyme** [Lord-of-the-Craft/tracker#386]
**Minecraft Username**
_mady07

**Describe the bug**
https://gyazo.com/59b097c92de01bf66ca387323416153b

**How did this occur**
Please explain what lead to this bug, and how we might reproduce it for testing.

**Expected behavior**
A clear and concise description of what you expected vs what actually occurred.

**Screenshots**

**Minecraft version:**
What Minecraft version are you using

**Additional context**

**Comment by The60th** [comment]
This is the intended behavior LC wipes all meta data.
