### ISSUE TITLE
Error in fishing loot item

### ISSUE THREAD

**Issue by grandpablue** [Lord-of-the-Craft/tracker#389]
**Issue**
Self explanatory, see attached:
<img width="708" alt="Screen_Shot_2023-11-16_at_1 30 05_pm" src="https://github.com/Lord-of-the-Craft/tracker/assets/79768296/b13cd74e-6e7a-4358-b353-f49f690311ae">

**Ticket refence number:**
RTS-139221

**Comment by Adelemphii** [comment]
fixed (a while ago)
