### ISSUE TITLE
Crafting Recipe's pull from single stacks rather than whole inventory

### ISSUE THREAD

**Issue by Deer2underscores** [Lord-of-the-Craft/tracker#40]
If you split a stack of coal for example into 32 and 32 and you're smelting a 64 stack of copper the plugin thinks you don't have enough coal for the recipe because it seems to be pulling from the single stacks and not the entire inventory.

SEE RTS #52245

**Comment by Nickrocky** [comment]
Fixed in 1.0.0 update, see [commit](https://github.com/Lord-of-the-Craft/lotc-master-vortex/commit/3cacf45a092eeede2b725d1990bb2f048543a526)
