### ISSUE TITLE
Persona's Inventories duping to another persona 

### ISSUE THREAD

**Issue by Aehkaj** [Lord-of-the-Craft/tracker#403]
**Minecraft Username**
ColonelAehkaj

**Describe the bug**
The inventory from one of my persona slots duplicated over to another, replacing what was in that persona's inventory

**How did this occur**
I honestly can't tell. I just swapped personas a few times after an ST event and never noticed until the next day where I thought I was on the right slot despite not being on that slot at all.

**Minecraft version:**
1.18.2 fabric loader client

**Additional context**
I have no more context or info that can help

**Comment by Kowagirl** [comment]
Fixed by https://github.com/Lord-of-the-Craft/lotc-master-archecore/issues/14
