### ISSUE TITLE
Missing / deleted my items

### ISSUE THREAD

**Issue by SSR150** [Lord-of-the-Craft/tracker#412]
**Minecraft Username**
SSR150

**Describe the bug**
I logged on today and my items were missing from my inventory the date is 3/18/2024

**How did this occur**
I am unsure as I logged on, voted, and realized "oh all of my items are missing maybe its a visual glitch" then whe nI relogged they were all still gone

**Expected behavior**
I am unsure as all of my items are missing, i have no clue what caused it

**Screenshots**

**Minecraft version:**
1.19.3 curseforge

**Additional context**
![problem](https://github.com/Lord-of-the-Craft/tracker/assets/113811577/d83b6b0d-7655-4a73-8947-3670f39c0f92)

**Comment by TheRanTan** [comment]
https://www.lordofthecraft.net/forums/topic/234709-handling-inventory-restores/
