### ISSUE TITLE
Berserker Axe

### ISSUE THREAD

**Issue by wowj2** [Lord-of-the-Craft/tracker#426]
**Minecraft Username**
lector

**Describe the bug**
By edit roleplaying a berserker axe, it allows the wielder to negate the reduced armor effect, whilst also having the same/a similar strength to a normal, non-roleplay signed berserker axe.

**How did this occur**
/edit roleplaying a berserker axe.

**Expected behavior**
The Axe to do the same dmg as a punch, like the other pvp items once given the roleplay tag.

**Screenshots**

https://github.com/Lord-of-the-Craft/tracker/assets/168715174/6f7c6a45-de69-43a5-bfd2-1045d7301c87

**Minecraft version:**
1.18.2

**Comment by TheRanTan** [comment]
I think this is a QOL thing

**Comment by The60th** [comment]
I still get this notifications so.... But this is not a quality of life bug, this allows the player to remove the armor debuff from the weapon yet still deal full damage.  This effectively allows a player to use the highest possible DPS weapon with zero draw back. Should be consider high priority fix. 

@greehny @wowj2 @TheRanTan  @Kowaman

**Comment by Kowagirl** [comment]
Closed by https://github.com/Lord-of-the-Craft/Surge/pull/5/commits/a66817e5c8b41ef8e5e149a5c54b17b606a28cd9
