### ISSUE TITLE
Cannot send messages on server

### ISSUE THREAD

**Issue by elliotido** [Lord-of-the-Craft/tracker#43]
When I connect to the server on 1.15.2 client, I am unable to use server chat, such as #q, #rp, and #ooc, and #st. I remain able to interact with the world and play, and harvest nodes and everything else. I am also able to use my staff pex, I just cannot type outside of /msg. 

![image](https://user-images.githubusercontent.com/75703284/101551083-4e1dfb80-3965-11eb-9262-d7bced7ee637.png)

It does not work on my main (Worldeater) or my alt (Mumkey), so it seems related to my ip that I connect with. I cannot send messages in lobbies either.

**Comment by CommissarVoop** [comment]
The issue follows on the all server, not just on the lobby server. A Proxy restart was made and nothing fixed it.

**Comment by elliotido** [comment]
Chat settings somehow carried over from Lunar client as "Commands Only". My bad! Thanks so much for the help, either way.

**Comment by MCVDK** [comment]
Llir said to close this ticket, woop.
