### ISSUE TITLE
Shop Losing Item Count on Restarts

### ISSUE THREAD

**Issue by HobbitForHire** [Lord-of-the-Craft/tracker#433]
**Issue**
Raised by xo31khov
Each restart, their shop at 2598 -5 2620 has shop-slabs that reduce down to 0 items, despite their shop chest containing items
Confirmed the issue on their shop
Unable to replicate elsewhere

**Ticket refence number:**
RTS-155552

**Comment by Kowagirl** [comment]
I've heard enough reports on this where I'm going to mark it as confirmed, though root cause is unknown.
