### ISSUE TITLE
[Dev Server] Signs Editable

### ISSUE THREAD

**Issue by TheRanTan** [Lord-of-the-Craft/tracker#447]
**Minecraft Username**
The_Ran_tan

**Describe the bug**
All signs, specifically lift signs, are editable by all players allowing them to disable lifts (RP Signs are NOT affected)

**How did this occur**
Place any non-rp sign and you can edit it

**Expected behavior**
unable to edit signs or the ability to lock signs

**Screenshots**

**Minecraft version:**
1.18.2

**Comment by Kowagirl** [comment]
Related Craftbook issue https://github.com/EngineHub/CraftBook/issues/1325, though I was able to fix it with a small patch in AtlasModule.
