### ISSUE TITLE
/apply bug

### ISSUE THREAD

**Issue by snoopie12** [Lord-of-the-Craft/tracker#45]
MC Names of all involved: N/A

Description: When doing /apply it should give the new players a link to our apply page at the forums. Instead the players are unable to click the link and so can not go to the website through the command. 

Date of occurance: Since map change. 

In game specifications: N/A

Steps to Reproduce
Step 1: /apply
Step 2: Click the apply link

Expected Behavior: It brings you to the apply page of the website

Actual Behavior: New players cant actually click it, it does nothing.

**Comment by Kowaman** [comment]
Fixed
