### ISSUE TITLE
Crash Upon Messaging

### ISSUE THREAD

**Issue by MiniMuffinNinja** [Lord-of-the-Craft/tracker#5]
MC Names of all involved: MiniMuffinNinja

Description: Whenever I send a message in chat, within a few moments, the server will kick me

Date of occurrence: 8/22/2020

Steps to Reproduce

Step 1: Enter LotC
Step 2: Send a message in chat (any)
Step 3: Wait a few moments
Step 4: Server kicks you
Expected Behavior
I should be able to send a message in chat

Actual Behavior
I crash upon sending the message

Additional Information: None

Error Message: Internal Exception: java.io.IOException: An existing connection was forcibly closed by the remote host

**Comment by MiniMuffinNinja** [comment]
Thanks! Sorry for taking so long to respond, I did what you said and it worked! Thanks again

**Comment by CommissarVoop** [comment]
No problem, I'm happy to hear that the issue was solved. Thank you for the report, have a wonderful today!
