### ISSUE TITLE
Joining bug

### ISSUE THREAD

**Issue by snoopie12** [Lord-of-the-Craft/tracker#50]
MC Names of all involved: N/A

Description: When joining the server for the first time new players appear to spawn in the void. 

Date of occurance: Since Almaris

Steps to Reproduce

Step 1: Join the server with a minecraft account that has just been accepted. 
Step 2: You start in the void. 

Expected Behavior: You start at the spawn spot.

Actual Behavior: You spawn in the void. 

Additional Information: This doesnt apply to wondering souls for some reason.

**Comment by Kowaman** [comment]
Was an error in the config file giving an incorrect tutorial location. Fixed for the next restart.
