### ISSUE TITLE
Berry Bush Armor Durability Damage

### ISSUE THREAD

**Issue by Deer2underscores** [Lord-of-the-Craft/tracker#53]
Armor breaks incredibly fast while moving around in a berry bush, whether in god mode or not. Standing still does not cause any damage to armor

**Comment by Nickrocky** [comment]
This is a minecraft bug, there sadly isnt a DamageCause, or even DamageType for berry bushes or cacti. This is a currently marked bug on Minecrafts bug tracker. So this is a wontfix

**Comment by Kowaman** [comment]
https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/entity/EntityDamageByBlockEvent.html @Nickrocky
