### ISSUE TITLE
stuck in the void

### ISSUE THREAD

**Issue by z0m-be** [Lord-of-the-Craft/tracker#55]
i've been stuck inside of the void for a day now, i cant play or get out. its annoying 
![2020-12-14_15 15 51](https://user-images.githubusercontent.com/48593459/102160818-030b5900-3e3b-11eb-8ec8-dcaaeda89784.png)

**Comment by Kowaman** [comment]
This bug was fixed this afternoon so it wont happen in the future. Please make a /modreq in game and they can teleport you out to spawn.

**Comment by z0m-be** [comment]
> This bug was fixed this afternoon so it wont happen in the future. Please make a /modreq in game and they can teleport you out to spawn.

yes but im still falling through the map, i've sent 4 or 5 requests now. thanks for the reply though
