### ISSUE TITLE
Armor and Sword Durability bug

### ISSUE THREAD

**Issue by Orlanth-MC** [Lord-of-the-Craft/tracker#57]
Orlanth

Any time an item can't be used it'll still tick a durability (specifically weapons and armor, unsure about breaking blocks). For example, soulbound, statused the same as someone and hitting, hitting someone at CT. 

Mickaelhz hit me at CT and all my armor broke. Also tried it with a soulbound item toady just to test it out.

I expected my armor to not lose durability when I was punched and not damaged, but it was.

1.15.2

**Comment by Kowaman** [comment]
Related to https://github.com/Lord-of-the-Craft/tracker/issues/56
