### ISSUE TITLE
the blast furnace wont give me my ores back

### ISSUE THREAD

**Issue by z0m-be** [Lord-of-the-Craft/tracker#58]
LongNosePug

i went mining, i came out and put my ores into a smelter. i come back in a second with a bucket and it just keeps giving me the same message "there seems to be still molten metal in there, perhaps you should get a bucket" but i already have a bucket.

i went mining, i put my ores into a blast furnace (the one in the druids place) i come back with a crafted bucket and it wont give me my ores. 

it is supposed to give me a bucket full of molten metal, instead of an error message

![2020-12-15_22 02 17](https://user-images.githubusercontent.com/48593459/102311192-43450700-3f21-11eb-9402-1b661c37f514.png)

1.16.4

it was working fine before

**Comment by MCVDK** [comment]
Did a few attempts with different time periods of waiting and different forms of buckets -- none left the issue presented here and gave the ore required. Issue might've been waiting too little time for the ore to smelt.

**Comment by Nickrocky** [comment]
You cannot use stacks of buckets to pick up molten metal
