### ISSUE TITLE
Herbs in Pots

### ISSUE THREAD

**Issue by Coennrad** [Lord-of-the-Craft/tracker#69]
**Minecraft Username**
Coennrad

**Describe the bug**
Once one puts an alchemical herb, with name and description, into a clay pot and then breaks it, the herb loses all the properties and reverts back to a basic minecraft item.

**How did this occur**
I put an official herb into a pot, broke the pot, found the bug.

**Expected behavior**
Herbs should retain their properties after the pot they're in is destroyed, and the herb's name should show up above the pot when one hovers over it, similar as to how item frames work.

**Screenshots**

**Minecraft version:**
1.16.4

**Additional context**

**Comment by Deer2underscores** [comment]
Use item frames or just dont place them in pots. Use regular plants, place in pots, use a sign to describe a plant being in it.

This won't be fixed.
