### ISSUE TITLE
Breeding Animal Energy Bug

### ISSUE THREAD

**Issue by MCVDK** [Lord-of-the-Craft/tracker#72]
Logging out after breeding animals let's you dodge the vortex energy drain. (Submitted by DiscoLiquid)

See RTS-54154

**Comment by Deer2underscores** [comment]
I couldn't replicate it on the dev server but I think it may work if you have someone else around to keep the chunk loaded in while the animals do their thing.

**Comment by Kowaman** [comment]
Duplicate of #59
