### ISSUE TITLE
Allow selling and buying for hundredths of mina instead of only tenths

### ISSUE THREAD

**Issue by Deer2underscores** [Lord-of-the-Craft/tracker#73]
Problem: 
Players want to sell things for less than tenths of mina, i.e. cobblestone for .01 instead of .1

Solution: 
Allow player shops to sell items for hundredths of mina instead of only tenths

Additional context: 
This was a player suggestion by jameson_h on the Official LotC discord that I think should be easy enough and a good enough QoL feature.

**Comment by Kowaman** [comment]
This is not QoL, the mina system is designed in many places around tenths of mina being the smallest denomination,
