### ISSUE TITLE
Bookshelves eating Books

### ISSUE THREAD

**Issue by Deer2underscores** [Lord-of-the-Craft/tracker#77]
**Issue**
Several players, only one ticket, have reported losing their books when placing a book within a bookshelf, leaving for a short period of time then coming back to open the shelf. They find their book to be gone entirely.

**Ticket refence number:**
RTS-54663

**Comment by MCVDK** [comment]
After placing a couple of bookshelves (with different locks: one without -- one with donation -- one with public -- one with private) for 1 day the books did not disappear from the bookshelves. Issue might be related to #8 with people removing the books from the bookshelves.

**Comment by FallenVibe** [comment]
RTS 106669
![image](https://user-images.githubusercontent.com/48634310/180676055-bb8ab44d-47ea-4cd4-9a91-123a8d103fe9.png)

Seems the issue, or something similar, has come up again. The bookshelf on this ticket was unlocked when checked, but did not have any logs of a book being withdrawn.

Could possibly be an issue with omni not logging something.
