### ISSUE TITLE
Lead Recipe Stealing Thread

### ISSUE THREAD

**Issue by Deer2underscores** [Lord-of-the-Craft/tracker#78]
**Issue**
Player crafted 16 leads with a craft table like this [CTx16][CTx16][X]
                                                                              [CTx16][CIx16][X]
                                                                              [X]        [X]      [CTx32]

They lost the entire stack of 32 cotton thread, meaning 16 cotton thread was eaten up by it.
**Ticket refence number:**
RTS-54537

**Comment by Nickrocky** [comment]
Could not replicate, if the issue re-occurs someone will make a Treq
