### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by astiengreenhart** [Lord-of-the-Craft/tracker#79]
Username: AstienGreenhart

Bug Description:
Commands not working after a period of time

What led to this:
Logging into LoTC, kicked multiple times with message "Existing Connection Was Forcibly Closed By A Remote host". I logged in finally, and behaviour was normal for about 60 seconds, after which, I tried inputting a command, and nothing happened. No results, no error messages, nothing. It was like it didn't see the commands. Commands did work for the first minute after I logged in, and chat worked. I relogged several times, restarted my computer, and tried rebooting the minecraft launcher. Commands work on all other servers. The same results each time I log in.

Expected Behaviour:
For the commands to work normally.

No screenshots, can't take a screenshot of nothing happening.

Minecraft version: 1.15.2

**Comment by Deer2underscores** [comment]
Does this happen every single time or only on occasion?

**Comment by astiengreenhart** [comment]
It happens every time. I asked ingame and apparently some other players have had the problem too.

**Comment by Kowaman** [comment]
This is due to a connection issue. Consider playing with your DNS settings, or using a VPN service such as Warp by Cloudflare (free) https://1.1.1.1/
