### ISSUE TITLE
Donation Bookshelf Bug

### ISSUE THREAD

**Issue by peachcool** [Lord-of-the-Craft/tracker#8]
MC Names of all involved:
peachcool 

Description
Any player can take out books from a donation bookshelf despite not being added. This happened in the Haelunor library but I believe its a server wide bug.

Date of occurrence:
2020-09-02

In game specifications

Steps to Reproduce

Step 1: Normal player opens donation bookshelf without being added to the shelf
Step 2: Normal player takes book.

Expected Behavior
You're not supposed to be able to take books from donation shelves

Actual Behavior
You can take books from donation shelves.

Additional Information
![image](https://user-images.githubusercontent.com/70682901/92075808-228be380-ed6e-11ea-9af1-636dff8725b6.png)
in this image we tested it and it is able to be logged on omni if that helps any.

Error Message
?

**Comment by MCVDK** [comment]
Had two players (and a story team member) test the issue -- both of the regular players could not remove the book from the bookshelf though the story team member could (likely due to PEX)

**Comment by peachcool** [comment]
The bug was in last map if that helps any.

**Comment by Nickrocky** [comment]
Seemed to have been an odd fluke, we were having some troubles with LWC a while back, but after testing with a lot of books, I could not replicate the behavior. Though another bug was found regarding donation shelves. See my other report for that bug, all things considered, this can be closed as it just isn't applicable anymore.
