### ISSUE TITLE
Vortex Stone Bucket crafting crashes Minecaft

### ISSUE THREAD

**Issue by Reznc** [Lord-of-the-Craft/tracker#85]
**Minecraft Username**
Reznc

**Describe the bug**
Crafting a stone bucket crashes Minecraft

**How did this occur**
I crafted a stone bucket

**Expected behavior**
You get a stone bucket without Crashing.

**Screenshots**
N/A

**Minecraft version:**
Minecraft 1.16.4 (OptiFine 1.16.4 HD U G5)

**Additional context**
N/A

**Comment by Deer2underscores** [comment]
Play on server version 1.15.2

**Comment by Reznc** [comment]
The bug did not occur when I used version 1.15.2.
