### ISSUE TITLE
Tab bug

### ISSUE THREAD

**Issue by snoopie12** [Lord-of-the-Craft/tracker#9]
MC Names of all involved: Everyone online at the moment, too much to name. 

Description: The tab with names was completely messed up and didnt went back to normal by relogging. 

Date of occurance: 3-9-2020

In game specifications: The order of persons at the tab was completely messed up. 

Steps to Reproduce

Step 1: Press 'tab' 
Step 2: Look over it

Expected Behavior:  A normal tab shows up

Actual Behavior: Its completely messed up. The order is not there. 

Additional Information:
https://cdn.discordapp.com/attachments/427582167330193418/751129528352505956/unknown.png

**Comment by Nickrocky** [comment]
I think that NPC's are being counted into the tab sorter, I have 0 ideas why but Voop and I were finding NPC skins on the tab this morning
