### ISSUE TITLE
RP item formatting bug

### ISSUE THREAD

**Issue by Chorale18** [Lord-of-the-Craft/tracker#92]
**Issue**
In the words of the reporter, "If you do /edit roleplay after you already made the item description, it'll replace the first line of the description with blue text". 

**Ticket refence number:**
RTS- 55582

**Comment by Deer2underscores** [comment]
Had this issue once before but chalked it up to a one time issue because it worked when I took their ticket. See if they have this problem with any other items on top of seeing what item originally had the issue.

**Comment by MCVDK** [comment]
After multiple attempts at recreation there was no success -- It would simply replace the vortex tag.
