### ISSUE TITLE
Lost access to former staff persona slots.

### ISSUE THREAD

**Issue by JustGrim** [Lord-of-the-Craft/tracker#94]
**Minecraft Username**
Please input your Minecraft username
StudioGrimly, formerly JustGrim
**Describe the bug**
The bug occurred on 2021/01/25 and came with the persona slot changes, it made all former staff who had their persona slots since leaving staff removed.
**How did this occur**
Please explain what lead to this bug, and how we might reproduce it for testing.
By doing whatever you did to the persona slots with the changes,
**Expected behavior**
A clear and concise description of what you expected vs what actually occurred.
I expected to be able to access my Persona slots I've had since leaving ST in mid 2020, instead I can't open them and lost items
**Screenshots**
https://gyazo.com/c2cc8dc99b8f7ce8c4482ff85e336198
**Minecraft version:**
What Minecraft version are you using
1.15.2
**Additional context**

**Comment by Chorale18** [comment]
This is intentional. Since you are no longer on Staff, you will not have access to the slots. You can always upgrade your VIP or server boost the LOTC discord to get access to another!
