### ISSUE TITLE
Sneaking prevent AFK kick

### ISSUE THREAD

**Issue by Deer2underscores** [Lord-of-the-Craft/tracker#95]
**Issue**
Sitting afk in /sneak prevents players from being moved to the lobbies.

**Ticket refence number:**
RTS-55686

**Comment by MCVDK** [comment]
AFK kicking is currently disabled -- so this issue cannot be replicated for the moment.

**Comment by Kowaman** [comment]
Fixed by https://github.com/Lord-of-the-Craft/lotc-master-bungee-argus/commit/b3c729ee0608c9dbcb32bfd59aad86a0f6257ff7
