### ISSUE TITLE
/ascend and /descend permissions

### ISSUE THREAD

**Issue by MCVDK** [Lord-of-the-Craft/tracker#96]
**Issue**
/ascend and /descend are open-use which can [possibly] allow people to enter into areas unavailable to them. 

**Ticket refence number:**
RTS-55811

**Comment by MCVDK** [comment]
After testing this seems to be an issue for a singular individual only (puffables). It might be due to former staff permissions-- as a triage member I did not have access to the command but the player can do it. Equally as important to inquire about. 

Uncertain as to which project this would fall under-- feel free to assign a project.

**Comment by Kowaman** [comment]
User had residual world edit pex
