### ISSUE TITLE
The vortex mobs are fucked and we dont wanna rollback so please fix

### ISSUE THREAD

**Issue by Terrarath** [Lord-of-the-Craft/tracker#99]
Turns out the bears are reskinnned zombie piglins. Found this out because there spawning without there +150 hp helmets, as piglins with no spawn cap. 

And they still drop bear leather and steaks- Leopard man has already reported this but rollbacks are annoying as hell so we are tryna report asap

**Comment by Nickrocky** [comment]
This happened because LibDisguises was temporarily disabled to combat lag, so Vortex wasnt able to apply disguises to hunting mobs. This isn't really a bug that needs to be fixed but yeah, it shouldnt happen again after we change NPC's.
